import asyncio
import datetime
from waybackpy import WaybackMachineCDXServerAPI

# optimze code to wait a minute when getting server connection error before doing the next retry

retry_urls = ['https://www.brandonsun.com/national/breaking-news/winnipeg-jury-to-begin-second-day-of-deliberations-in-tina-fontaine-murder-trial-474805893.html', 'http://rabble.ca/news/2015/02/harpers-record-refusal-act-violence-against-indigenous-women', 'http://www.cheknews.ca/national-inquiry-into-mmiwg-set-to-release-plans-in-vancouver-344284/', 'https://www.cjme.com/syn/653/561976/sask-polytechnic-marks-mmiwg-national-awareness-day/', 'http://www.princegeorgecitizen.com/news/national-news/canadian-tragedy-of-missing-murdered-indigenous-women-dates-back-decades-1.2315809', 'http://www.thesuburban.com/life/lifestyles/stolen-sisters-looks-at-tragedy-of-missing-and-murdered-indigenous/article_a0605255-9426-5c30-ac21-578cc84f4e1c.html', 'http://www.huffingtonpost.ca/2018/01/11/mmiwg-inquiry-loses-yet-another-executive-director_a_23331305/', 'https://www.thecentralvoice.ca/news/regional/update-national-inquiry-into-missing-and-murdered-indigenous-women-releases-final-report-317953/', 'https://theturtleislandnews.com/index.php/2021/09/24/activists-mp-say-trudeau-failed-to-act-on-mmiwg-will-he-act-now/', 'http://www.lillooetnews.net/indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered-missing-women-1.2967661', 'https://rock101.com/news/10005003/national-day-of-action-mmiwg-calls-for-justice/', 'http://www.nationalobserver.com/2015/09/13/news/mulcair-promises-inquiry-missing-and-murdered-indigenous-women', 'https://www.piquenewsmagazine.com/whistler/bc-premier-promises-action-after-release-of-missing-women-inquiry-report/Content?oid=13930393', 'https://thetyee.ca/News/2023/02/15/Justin-Trudeau-Say-Their-Names/', 'https://www.chrisd.ca/2018/08/02/serena-mckay-teen-deadly-beating-manitoba-vsentence/', 'http://www.durhamregion.com/news-story/5951675-b-c-tory-candidate-says-views-not-contradictory/', 'https://pjmedia.com/news-and-politics/blame-bad-decisions-for-crime-not-structural-racism-and-colonialism/', 'https://theturtleislandnews.com/index.php/2023/01/09/its-not-just-about-my-sister-anymore-says-mmiwg-activist/', 'http://www.huffingtonpost.ca/2014/08/27/thomas-mulcair-native-aboriginal-inquiry_n_5722916.html', 'http://medicinehatnews.com/news/national-news/2017/03/28/missing-murdered-women-inquiry-to-hold-first-hearing-may-29-in-whitehorse/', 'http://www.reachfm.ca/christian-news/this-report-is-also-about-hope-national-inquiry-reveals-genocide-against-indigenous-women-and-girls-opportunity-to-do-better', 'https://medicinehatnews.com/news/national-news/2019/06/05/indigenous-police-chief-calls-for-governments-to-implement-mmiwg-recommendations/', 'http://www.ngnews.ca/news/regional/2017/4/3/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories.html', 'http://news.findlaw.com/apnews/a681280195334d44803f289a140a1dbf', 'https://aptnnews.ca/2020/03/11/manitobas-project-devote-a-waste-of-time-when-it-comes-to-solving-murders-of-indigenous-women/', 'https://aptnnews.ca/2019/12/05/after-undrip-mmiwg-commitments-attention-turns-to-throne-speech-for-hint-of-what-comes-next/', 'http://www.cranbrooktownsman.com/national/417991293.html', 'http://www.thetelegram.com/news/regional/2017/4/3/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories.html', 'http://wawa-news.com/tag/aboriginal-news/', 'http://medicinehatnews.com/news/national-news/2017/10/27/national-inquiry-urged-to-hear-voices-of-indigenous-women-in-prison/', 'http://morningstaronline.co.uk/a-cadf-Canada-to-face-its-racism-demons', 'https://www.nsnews.com/federal-delay-of-mmiwg-action-plan-sparks-dismay-ahead-of-inquiry-anniversary-1.24145128', 'http://www.ctvnews.ca/politics/families-call-for-hard-reset-of-mmiwg-inquiry-1.3537010', 'http://www.newswire.ca/en/story/1559363/assembly-of-first-nations-national-chief-says-rcmp-update-on-missing-and-murdered-aboriginal-women-an-urgent-call-to-action-on-a-national-crisis', 'http://paherald.sk.ca/2019/06/03/this-is-genocide/', 'http://medicinehatnews.com/news/national-news/2015/11/09/we-need-to-get-this-right-missingwomen-groups-urge-caution-before-inquiry/', 'http://www.thewesternstar.com/news/regional/2017/4/3/missing-and-murdered-women-s-inquiry-not-reaching-out-to-families-advocates.html', 'https://thetyee.ca/Analysis/2023/04/17/Better-Future-For-Downtown-Eastside/', 'http://www.calgarysun.com/2015/10/06/sisters-in-spirit-vigil-in-calgary-draws-hundreds-for-national-day-of-action-for-murdered-and-missing-aboriginal-women', 'http://theturtleislandnews.com/index.php/2018/02/22/accused-death-tina-fontaine-not-guilty-murder/', 'http://www.fftimes.com/news/local/news/mmiwg-calls-action-highlighted-council', 'http://cfnrfm.ca/national-inquiry-into-missing-and-murdered-indigenous-women-and-girls-in-vancouver/', 'https://www.pentictonherald.ca/news/national_news/article_ee2a09f3-d7ab-5250-a888-2df4f41f9c31.html', 'http://www.wdio.com/news/thunder-bay-missing-and-murdered-indigenous-women-and-girls-inquiry/4695960/?cat=10335', 'http://cjme.com/article/357415/man-accused-killing-teenager-tina-fontaine-scheduled-be-winnipeg-court', 'http://www.fftimes.com/news/global/national/13m-earmarked-mmiwg-projects', 'http://www.qctonline.com/slc-students-learn-about-national-inquiry-missing-and-murdered-indigenous-women-and-girls', 'http://www.voiceonline.com/attorney-general-suzanne-anton-says-b-c-will-participate-fully-in-national-inquiry/', 'http://www.parrysound.com/news-story/6194442-man-accused-of-killing-teen-to-be-in-court/', 'https://www.piquenewsmagazine.com/whistler/indigenous-day-part-2-police-chief-says-vpd-values-its-relationship-with-indigenous-people/Content?oid=15514491', 'http://www.cheknews.ca/national-inquiry-into-mmiwg-set-to-release-plans-in-vancouver-344284/', 'https://www.cjme.com/syn/653/561976/sask-polytechnic-marks-mmiwg-national-awareness-day/', 'http://aptn.ca/news/2016/08/03/meet-the-commissioners-that-will-lead-the-mmiw-national-inquiry/', 'http://lethbridgeherald.com/news/national-news/2016/08/03/canadian-tragedy-of-missing-murdered-indigenous-women-dates-back-decades/', 'https://www.simcoe.com/news-story/10013469-feds-get-a-fail-for-lack-of-mmiwg-action-plan/', 'http://www.cjme.com/syn/653/184464/mmiwg-inquiry-addresses-questions-on-after-care-for-families', 'https://www.thewesternstar.com/news/canada/indigenous-art-on-billboards-part-of-canadian-mmiwg-awareness-campaign-324940/', 'http://aptn.ca/news/2016/08/03/minister-of-indigenous-affairs-discusses-mmiw-national-inquiry/', 'https://www.thebeaverton.com/2020/06/country-responsible-for-the-indian-act-chinese-head-tax-komagata-maru-africville-none-is-too-many-japanese-internment-camps-sixties-scoop-residential-schools-oka-crisis-and-mmiwg-declares-itsel/', 'http://ipolitics.ca/tag/metis/', 'http://www.brandonsun.com/national/breaking-news/missing-and-murdered-womens-inquiry-not-reaching-out-to-families-advocates-417989893.html', 'https://paherald.sk.ca/2019/06/29/police-chief-vows-to-address-national-inquiry-recommendations/', 'https://www.chatelaine.com/news/recommendations-mmiwg-final-report/', 'https://lethbridgeherald.com/news/national-news/2020/11/18/rcmp-needs-structural-changes-to-address-racism-mmiwg-commissioner/', 'https://theturtleislandnews.com/index.php/2021/06/08/ottawas-action-plan-for-the-natl-inquiry-on-mmiwg-is-fundamentally-flawed-says-nwac/', 'https://www.yahoo.com/lifestyle/shocking-little-done-native-women-150000805.html', 'https://www.thestar.com/entertainment/stage/opinion/2018/12/18/robert-lepages-kanata-pisode-1-la-controverse-misses-the-mark.html', 'https://thetyee.ca/News/2022/08/29/Missing-Women-Salmon-River-Valley/', 'http://www.cfra.com/NationalCP/Article.aspx?id=500869', 'http://aptn.ca/news/2016/02/19/a-look-at-the-work-behind-the-mmiwg-pre-inquiry-consultations/']
more_bad_request = ['http://rabble.ca/blogs/bloggers/krystalline-kraus/2015/03/no-justice-no-peace-honouring-cindy-gladue', 'https://www.news.com.au/travel/travel-updates/incidents/what-canadas-notorious-highway-of-tears-is-really-like/news-story/a1143fac6ee183ec7f7b5a608acec2a8', 'http://www.livenewscentral.com/calls-of-justice-for-aboriginal-women-echo-down-canadas-highway-of-tears/', 'http://www.journalpioneer.com/Living/2016-10-01/article-4654605/Confederation-Landing-in-Charlottetown-to-host-Sisters-in-Spirit-Vigil/1', 'https://www.timescolonist.com/highlights/opinion-from-red-dresses-to-memory-stones-collaborative-and-replicable-activism-can-help-causes-gain-momentum-5331774', 'https://www.nationalobserver.com/2023/12/15/news/feds-consultations-red-dress-alert', 'https://www.toronto.com/things-to-do/books-and-authors/once-homeless-hitchhiking-on-b-c-s-highway-of-tears-angela-sterritt-s-now-a/article_3fa51384-c405-5776-855d-cd15777329b1.html', 'https://www.thestar.com/calgary/2018/10/04/sisters-in-spirit-gather-strength-at-calgary-rally-for-missing-and-murdered-indigenous-women.html', 'http://www.kelownadailycourier.ca/entertainment/article_d7a87f36-4721-11e7-a5ef-77c56794aadc.html', 'http://www.burlington-record.com/ci_32569940/guest-commentary-red-dresses-are-stark-reminder-violence', 'http://www.hamiltonnews.com/news-story/6097413-deleted-emails-on-b-c-s-highway-of-tears-reopen-old-wounds/', 'https://fortsaskonline.com/articles/bon-accord-family-honours-missing-and-murdered-indigenous-women-and-girls-on-red-dress-day-', 'http://www.brandonsun.com/national/breaking-news/bc-documents-on-highway-of-tears-open-wounds-as-missing-women-inquiry-looms-342876752.html', 'http://lethbridgeherald.com/news/national-news/2015/11/08/bc-documents-on-highway-of-tears-open-wounds-as-missingwomen-inquiry-looms/', 'http://www.chroniclejournal.com/news/national/families-walk-highway-of-tears-before-missing-murdered-indigenous-women/article_eb0eda92-a659-514f-b4dd-da65b0764454.html', 'http://www.paherald.sk.ca/Canada---World/News/2015-11-08/article-4336382/B.C.-documents-on-Highway-of-Tears-open-wounds-as-missing-women-inquiry-looms/1', 'https://www.durhamregion.com/news-story/7574733-highway-of-tears-walk-to-wrap-before-mmiw-hearing/', 'http://www.bendbulletin.com/nation/4364665-151/dozens-lost-on-highway-of-tears', 'https://www.guelphmercury.com/news-story/7574733-highway-of-tears-walk-to-wrap-before-mmiw-hearing/', 'https://www.estevanmercury.ca/b-c-and-federal-governments-promise-unbroken-cell-service-on-highway-of-tears-1.24304358', 'https://theturtleislandnews.com/index.php/2021/04/07/b-c-and-federal-governments-promise-unbroken-cell-service-on-highway-of-tears/', 'http://www.adn.com/nation-world/2016/5/24/calls-of-justice-for-aboriginal-women-echo-down-canadas-highway-of-tears/', 'https://www.thestar.com/news/canada/2016/06/15/bc-to-provide-bus-service-on-notorious-highway-of-tears-by-end-of-year.html', 'http://www.thetelegram.com/Canada---World/News/2016-06-15/article-4560944/Highway-of-Tears-bus-service-to-run-from-Prince-George-to-Prince-Rupert/1', 'http://www.princegeorgecitizen.com/news/bc-news/via-rail-eyes-5-fares-to-vulnerable-on-highway-of-tears-1.2326402', 'http://www.princegeorgecitizen.com/news/business/smithers-highway-of-tears-gathering-another-roadblock-or-road-to-bus-line-1.2117045', 'http://www.huffingtonpost.ca/2015/12/14/highway-of-tears-transit_n_8807968.html', 'http://hollywoodlife.com/2016/09/27/kate-middleton-red-dress-canada-british-columbia-pics-royal-tour/', 'http://thetyee.ca/News/2015/11/04/Highway-of-Tears-FOI/', 'http://www.princegeorgecitizen.com/news/local-news/via-rail-in-talks-to-offer-5-fares-to-at-risk-groups-along-b-c-highway-of-tears-1.2326402', 'http://www.huffingtonpost.ca/2015/11/03/highway-of-tears-transit_n_8468060.html', 'https://www.wellandtribune.ca/news/red-dresses-hang-outside-brock-niagara-college-campuses-for-murdered-missing-indigenous-women/article_9e48bd50-0fc2-5de5-85a9-3185f79dee6c.html', 'https://www.stcatharinesstandard.ca/news/brock-university-niagara-college-hang-red-dresses-on-campus/article_780e5429-9d85-5975-b6ee-96ca011f5c6f.html', 'https://o.canada.com:443/news/provincial/murder-victims-daughter-calls-on-students-to-become-allies-to-indigenous-women', 'http://lethbridgeherald.com/news/national-news/2016/08/19/via-rail-in-talks-to-offer-5-fares-to-at-risk-groups-along-bc-highway-of-tears/', 'https://www.brandonsun.com/national/breaking-news/highway-of-tears-walk-to-wrap-in-smithers-bc-ahead-of-mmiw-inquiry-hearing-447577203.html', 'https://www.thestar.com/vancouver/2018/05/28/a-safe-harbour-for-women-fleeing-violence-on-bcs-highway-of-tears.html', 'https://www.terracestandard.com/home/highway-of-tears-public-transit-plan-wins-safety-and-security-awards/', 'https://aptnnews.ca/2018/11/21/red-dress-protest-for-cassidy-bernard-of-wekoqmaq-first-nation-closes-causeway-to-cape-cape-breton/', 'http://aptn.ca/news/2016/02/17/three-things-infocus-how-drag-the-red-helped-find-a-missing-man-indigenous-resistance-and-the-afns-energy-forum/', 'http://rabble.ca/news/2015/04/today-protests-demand-justice-cindy-gladue-follow-them-here', 'http://www.mykawartha.com/community-story/6194639-public-invited-to-screening-of-film-at-curve-lake-community-centre/', 'https://paherald.sk.ca/2021/05/05/i-wish-id-got-to-know-her-better/', 'https://www.leadertelegram.com/news/front-page/red-dress-display-recognizes-murdered-missing-indigenous-women/article_7330ccdc-f5d3-5156-9e1d-ed57865ec3f1.html', 'https://www.prairiepost.com/opinion/response-to-tragedy-in-kamloops-has-been-troubling/article_bd816fe8-c3b2-11eb-bb43-1fe096e1ab33.html', 'https://www.therecord.com/news-story/7576848-families-walk-highway-of-tears-before-missing-murdered-indigenous-women-hearing/', 'http://www.macleans.ca/news/highway-of-tears-bus-set-to-start-service/', 'https://www.thestar.com/news/canada/2016/08/19/via-rail-may-offer-5-fares-for-highway-of-tears-route.html', 'http://www.princegeorgecitizen.com/highway-of-tears-bus-starts-rolling-on-30-minute-trips-in-b-c-s-northwest-1.9243543', 'https://www.stcatharinesstandard.ca/news/words-are-not-enough-anymore-we-need-action-says-teen-survivor-during-red-dress-day/article_c886d4b1-6abc-5155-b894-2ee469e90cad.html', 'https://www.niagarafallsreview.ca/local-st-catharines/news/2023/04/27/heather-winterstein-to-be-remembered-on-red-dress-day.html', 'https://www.niagarafallsreview.ca/local-st-catharines/life/2023/05/05/our-indigenous-women-should-not-be-at-risk-wherever-they-go-rally-held-at-st-catharines-hospital-in-honour-of-heather-winterstein.html', 'https://theturtleislandnews.com/index.php/2023/03/27/we-must-be-found-mp-urges-feds-to-create-red-dress-alert-system-for-missing-indigenous-women-girls-and-two-spirit-people/', 'http://www.chroniclejournal.com/news/national/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous/article_735a46fe-8899-5128-aa4e-345f55ffb1c6.html', 'http://thechronicleherald.ca/canada/1504685-families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women', 'https://roundhouseradio.com/2017/09/20/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women/', 'http://www.huffingtonpost.ca/2017/09/25/mmiw-inquiry-families-walk-highway-of-tears-for-days-before-hearing_a_23222699/', 'http://www.timescolonist.com/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women-1.22855810', 'https://www.tbnewswatch.com/national-news/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women-721651', 'http://thechronicleherald.ca/canada/1505938-families-walk-highway-of-tears-before-missing-murdered-indigenous-women-hearing', 'http://www.timescolonist.com/families-walk-highway-of-tears-before-missing-murdered-indigenous-women-hearing-1.22994273', 'https://www.tbnewswatch.com/national-news/families-walk-highway-of-tears-before-missing-murdered-indigenous-women-hearing-725204', 'http://www.huffingtonpost.ca/2017/08/31/greyhound-plans-to-axe-route-along-b-c-s-highway-of-tears_a_23192936/', 'http://thechronicleherald.ca/business/1499517-greyhound-bus-route-on-b.c.s-highway-of-tears-one-of-five-that-could-be-axed', 'https://www.durhamregion.com/news-story/7587020-highway-of-tears-transit-lacking-advocates-say/', 'https://www.therecord.com/news-story/7587020-highway-of-tears-transit-lacking-advocates-say/', 'https://www.flamboroughreview.com/news-story/7587020-highway-of-tears-transit-lacking-advocates-say/', 'https://www.therecord.com/local-new-hamburg/news/2023/05/12/kids-at-new-hamburg-elementary-school-learn-about-red-dress-day.html', 'https://www.theuknews.com/news/272367467/minister-hutchings-and-minister-beare-met-with-local-lheidli-tenneh-first-nation-representatives-in-prince-george-regarding-the-highway-of-tears', 'https://fashionmagazine.com/flare/identity-politics/red-dress-day/', 'https://fashionmagazine.com/flare/identity-politics/red-dress-day/', 'https://opendemocracy.net/5050/audrey-huntley/breaking-one-of-canada', 'http://www.brockpress.com/2016/09/niagara-falls-comes-alive-with-the-night-of-art/', 'https://www.thestar.com/news/canada/2023/06/07/whats-blue-jean-jacket-day-how-organizers-hope-to-put-the-spotlight-on-violence-toward-indigenous-men.html', 'http://www.chroniclejournal.com/news/national/more-public-transit-still-needed-on-highway-of-tears-community/article_621729c6-3770-517a-8a9e-bb5b8efafcd6.html', 'http://www.journalpioneer.com/news/regional/2017/10/1/more-public-transit-still-needed-on-highway-of-tears-community-members-say.html', 'http://www.ngnews.ca/news/regional/2017/10/1/more-public-transit-still-needed-on-highway-of-tears-community-members-say.html', 'http://www.capebretonpost.com/news/regional/2017/10/1/more-public-transit-still-needed-on-highway-of-tears-community-members-say.html', 'https://www.tbnewswatch.com/national-news/more-public-transit-still-needed-on-highway-of-tears-community-members-say-730480', 'https://rapidcityjournal.com/news/red-dresses-displayed-to-evoke-the-loss-of-missing-and-murdered-indigenous-women/article_5cac85f0-7ea8-5c64-bc0d-973188ad40a2.html', 'https://www.newscenter1.tv/red-ribbon-skirt-society-hangs-up-red-dresses-for-missing-and-murdered-indigenous-women-awareness/', 'https://artvoice.com/2019/03/03/canadas-shameful-highway-of-tears/', 'https://www.sofmag.com/highway-of-tears-the-murders-in-indian-country-highway-of-tears-canada/', 'http://www.northernnews.ca/2016/09/22/kldcs-teacher-wins-international-teaching-award', 'https://www.thestar.com/news/canada/2017/10/01/highway-of-tears-needs-more-public-transit-community-members-say.html', 'https://www.union-bulletin.com/news/local/red-dress-display-aims-to-raise-mmip-awareness-in-walla-walla/article_76747844-eb7d-11ed-8ff9-1fb10c090e65.html', 'https://www.insideottawavalley.com/news-story/10202065-sisters-in-spirit-vigil-planned-for-oct-4-at-healing-forest-in-perth/', 'https://www.brandonsun.com/national/breaking-news/more-public-transit-still-needed-on-highway-of-tears-community-members-say-448892693.html', 'https://www.brandonsun.com/national/breaking-news/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women-446082083.html', 'https://theturtleislandnews.com/index.php/2023/02/22/ndp-mp-urges-feds-to-create-red-dress-alert-for-missing-indigenous-women/', 'http://lethbridgeherald.com/news/national-news/2017/09/20/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women/', 'http://theturtleislandnews.com/index.php/2019/05/08/six-nations-marked-red-dress-day-in-memory-of-murdered-and-missing-indigenous-women/', 'https://www.ojaivalleynews.com/culture/red-dress-day-casts-light-on-missing-murdered-indigenous-persons/article_66905bce-039a-11ef-8524-c36c89a92486.html', 'https://www.insideottawavalley.com/news/red-dress-ceremony-held-in-perth-on-may-5-to-mark-national-day-of-awareness/article_7f389397-97a3-518c-aef7-02d7dae2ecca.html', 'http://thechronicleherald.ca/artslife/1331375-maxine-noel%E2%80%99s-artwork-honours-missing-women', 'http://theturtleislandnews.com/index.php/2018/10/10/six-nations-marks-13th-annual-sisters-in-spirit-vigils/', 'https://www.thepeterboroughexaminer.com/news/faceless-dolls-exhibit-honours-missing-and-murdered-indigenous-women-girls-and-two-spirit-people/article_228db440-e2cb-5076-90bd-c067e67e6c1e.html', 'https://www.pentictonherald.ca/spare_news/article_6b6ad114-58fd-53a2-8ad4-bbe2c4885a82.html', 'https://www.torontotelegraph.com/news/274338193/government-of-canada-and-the-government-of-manitoba-announce-partnership-to-develop-a-red-dress-alert-together-with-indigenous-partners', 'https://montreal.ctvnews.ca/mapping-project-launched-to-give-voice-to-murdered-and-missing-indigenous-people-in-quebec-1.6385780', 'http://www.fftimes.com/news/local/news/red-dress-day-being-held-unfc-0', 'https://www.chroniclejournal.com/business/national_business/indigenous-leaders-want-corporate-reconciliation-efforts-to-extend-beyond-sept-30/article_f45bd956-9952-5bd9-9b50-eccf26883eec.html', 'https://www.toronto.com/news/wahta-mohawk-members-march-gather-in-solidarity-on-red-dress-day-may-5/article_15785f16-59c4-59d7-8f56-84c3500ef731.html', 'https://www.mississauga.com/news/wahta-mohawk-members-march-gather-in-solidarity-on-red-dress-day-may-5/article_53cb67b1-d3ec-5444-9209-2766ecc6583c.html', 'https://theturtleislandnews.com/index.php/2023/04/28/public-urged-to-take-part-in-red-dress-day-walk/', 'https://www.blackhillsfox.com/2023/04/26/inaugural-red-dress-gala-national-week-action-amplify-stolen-sisters-memories/', 'https://1005freshradio.ca/news/9670681/peterborough-national-red-dress-day/', 'https://www.piquenewsmagazine.com/human-resources-education/what-is-indigenous-peoples-day-the-annual-june-21-celebration-explained-7169611', 'https://thehill.com/blogs/blog-briefing-room/news/434901-red-dresses-hung-up-around-american-indian-museum-to', 'https://www.nationalobserver.com/2023/05/05/news/red-dress-day-honoured', 'https://www.thepeterboroughexaminer.com/ts/news/canada/2023/05/05/we-are-in-a-crisis-red-dress-day-honoured-as-leaders-say-more-work-to-be-done.html', 'http://www.startribune.com/canada-s-missing-women-of-the-highway-of-tears/380722371/', 'https://theturtleislandnews.com/index.php/2021/02/10/red-dresses-hang-in-the-trees-at-niagaras-post-secondary-institutions-to-symbolize-missing-and-murdered-indigenous-women/', 'https://theturtleislandnews.com/index.php/2022/05/11/from-red-dresses-to-memory-stones-collaborative-and-replicable-activism-can-help-causes-gain-momentum/', 'http://www.cjhk.ca/news/1601259081/students-mark-international-womens-day-red-dress-project', 'http://www.ckbw.ca/news/1601259081/students-mark-international-womens-day-red-dress-project', 'http://vanmag.com/city/theatre-review-missing-highway-of-tears/', 'https://thetyee.ca/News/2023/06/16/Butterflies-Spirit-Names/', 'https://www.pentictonherald.ca/news/article_71713784-0953-11ef-af1f-e3d681521603.html', 'https://www.saltwire.com/lifestyles/local-lifestyles/red-dress-installation-in-potlotek-first-nation-a-continued-call-for-justice-478072/', 'http://www.cjcyfm.com/news-and-info/medicine-hat-news/red-dresses-on-display-at-mhc/', 'http://www.timescolonist.com/highway-of-tears-bus-service-to-run-from-prince-george-to-prince-rupert-1.2279747', 'http://www.timescolonist.com/news/b-c/highway-of-tears-bus-service-to-run-from-prince-george-to-prince-rupert-1.2279747', 'http://www.princegeorgecitizen.com/news/bc-news/highway-of-tears-bus-service-to-run-from-prince-george-to-prince-rupert-1.2279747', 'http://www.princegeorgecitizen.com/news/bc-news/highway-of-tears-documents-open-wounds-as-inquiry-looms-1.2106507', 'http://www.princegeorgecitizen.com/news/local-news/highway-of-tears-documents-open-wounds-as-inquiry-looms-1.2106507', 'https://www.durhamregion.com/news-story/7566863-highway-of-tears-walk-to-honour-missing-murdered/', 'https://www.chroniclejournal.com/news/national/ndp-mp-urges-feds-to-create-red-dress-alert-for-missing-indigenous-women/article_c72f5d94-9e8f-514b-b0d8-806abc7ee7a2.html', 'https://foreignaffairs.co.nz/2024/05/06/mil-osi-translation-ministers-anandasangaree-hajdu-vandal-and-ien-issue-statement-on-red-dress-day-2024/', 'https://www.chroniclejournal.com/news/national/canada-manitoba-to-develop-red-dress-alert-for-missing-indigenous-women-and-girls/article_82c6a68d-836a-58e5-a008-debddf62956a.html', 'https://www.niagarafallsreview.ca/local-st-catharines/news/2023/05/02/there-is-still-so-much-that-people-should-learn-red-dress-day-walk-to-be-held-in-downtown-st-catharines.html', 'https://www.pentictonherald.ca/news/article_8f2c5084-0ca4-11ef-bb79-ab13101604f0.html', 'https://www.bramptonguardian.com/news/there-is-still-so-much-that-people-should-learn-red-dress-day-walk-to-be/article_7044c914-413e-5489-a68f-145811d21543.html', 'https://www.931theborder.ca/2019/05/03/red-dress-day-2019/', 'https://www.pentictonherald.ca/news/article_11be44a2-e91b-11ed-8ec9-1725fab0cb0e.html', 'https://theturtleislandnews.com/index.php/2021/05/05/may-5-national-red-dress-day/', 'https://www.kamloopsthisweek.com/news/kamloops-commemorates-red-dress-day-1.24315462', 'https://theturtleislandnews.com/index.php/2021/05/06/kamloops-commemorates-red-dress-day/', 'https://www.pentictonherald.ca/news/article_8d26a9f2-eb93-11ed-8b36-b33e37f99ee7.html', 'https://www.swiftcurrentonline.com/events/153959', 'https://fortsaskonline.com/articles/fort-saskatchewan-indigenous-society-hosts-event-for-red-dress-day', 'https://www.niagara-gazette.com/news/local_news/red-dress-exhibit-sheds-light-on-violence-aimed-at-native-women/article_1121f108-27a4-11ed-b495-bb6339ac161b.html', 'https://www.lockportjournal.com/community/red-dress-exhibit-sheds-light-on-violence-aimed-at-native-women/article_5fc8d8cd-da28-584e-bf25-a632efa2fd01.html', 'https://theturtleislandnews.com/index.php/2022/09/12/red-dress-exhibit-tells-the-stories-of-missing-murdered-indigenous-women-and-girls-through-family-narratives/', 'http://www.cheknews.ca/red-dress-project-remembers-missing-murdered-women-226602/', 'https://www.895thelake.ca/2021/05/06/treaty-3-police-launch-a-new-vehicle-decal/', 'http://www.brockpress.com/2015/10/sisters-in-spirit-vigil-honours-murdered-and-missing-aboriginal-women/', 'https://www.guelphmercury.com/whatson-story/7589961-guelph-to-host-sisters-in-spirit-vigil-wednesday/', 'http://www.insidehalton.com/news-story/5938181-sisters-in-spirit-vigil-takes-place-at-oakville-s-sheridan-college-oct-4/', 'http://www.ckrw.com/news/local-news/sisters-in-spirit-walk-and-vigil-held-in-whitehorse/', 'http://lethbridgeherald.com/commentary/letters-to-the-editor/2016/10/12/thanks-for-support-of-sisters-in-spirit-vigil/', 'http://www.prrecordgazette.com/2015/10/16/sisters-in-spirit-walk-a-heartfelt-gathering-of-support', 'http://www.prrecordgazette.com/2015/08/19/sisters-in-spirit-walk-in-the-works-for-october', 'https://www.thespec.com/events/7553332--sisters-in-spirit-vigil-in-honour-o/', 'http://www.comoxvalleyecho.com/news/special-events/highway-of-tears-film-screening-tuesday-july-21-1.2006529', 'http://aptn.ca/news/2015/09/09/stephen-harpers-longest-war-missing-and-murdered-indigenous-women/', 'https://www.montereycountynow.com/entertainment/art/a-movement-seeks-to-spread-awareness-about-missing-indigenous-peoples/article_83da00bc-0279-11ef-a87d-d3b42222749b.html', 'http://www.ngnews.ca/news/regional/2017/9/20/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women.html', 'http://www.capebretonpost.com/news/regional/2017/9/20/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women.html', 'http://www.theguardian.pe.ca/news/regional/2017/9/20/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women.html', 'https://www.thestar.com/news/canada/2017/01/27/highway-of-tears-partial-bus-service-ready-to-roll.html', 'http://www.trurodaily.com/news/regional/2017/9/20/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women.html', 'http://www.thewesternstar.com/news/regional/2017/9/20/families-walk-highway-of-tears-to-honour-missing-murdered-indigenous-women.html', 'https://medicinehatnews.com/news/national-news/2021/04/07/bc-and-federal-governments-promise-unbroken-cell-service-on-highway-of-tears/', 'https://www.chroniclejournal.com/news/national/in-the-news-for-may-5-a-look-at-aprils-employment-numbers/article_9c4e00c6-34cb-54b9-a902-228d422ef858.html', 'https://www.castanetkamloops.net/news/BC/485847/-Everything-is-one-The-healing-power-of-orphan-orca-whale-Kwiisahi-is-escape', 'https://ckfm.ca/2022/05/05/alberta-rcmp-raises-awareness-in-recognition-of-red-dress-day/', 'http://www.huffingtonpost.ca/news/highway-of-tears/', 'https://www.mississauga.com/opinion/11-year-old-mohawk-girl-on-the-mmiwg2s-emergency/article_01c57a6c-017b-5865-aa19-0f63d47a11e6.html', 'https://www.toronto.com/opinion/11-year-old-mohawk-girl-on-the-mmiwg2s-emergency/article_2f73ad1a-bc27-508a-8416-1f32b59309c2.html', 'http://www.journalpioneer.com/photo/2016-Sisters-in-Spirit-Vigil-3154468', 'https://www.streetinsider.com/Newsfile/CAP+Commemorates+Red+Dress+Day+and+Call+on+the+Federal+Government+to+Implement+a+Red+Dress+Alert/21621783.html', 'https://www.union-bulletin.com/news/local/red-dress-day-display-evening-vigils-bring-mmiw-awareness-to-walla-walla/article_1ef4fdda-0735-11ef-a7a6-8b21ab56b94a.html', 'https://www.therecord.com/news/waterloo-region/2023/05/05/waterloo-region-marks-red-dress-day.html', 'https://www.therecord.com/news-story/8947475-sisters-in-spirit/', 'https://www.montereycountyweekly.com/opinion/mcnow_intro/an-event-in-seaside-highlights-the-mostly-hidden-crisis-of-missing-indigenous-women/article_e8d3b718-eb84-11ed-8abc-cbda63394112.html', 'https://theturtleislandnews.com/index.php/2021/05/05/the-crisis-before-the-pandemic/', 'http://www.thepeterboroughexaminer.com/2016/01/23/missing-slain-not-forgotten', 'http://www.stcatharinesstandard.ca/2017/06/09/high-praise-from-six-nations-for-play-about-mmiwgs', 'http://www.mykawartha.com/whatson-story/5524765-weekend-wanderings-acclaimed-highway-of-tears-doc-screened-sunday/', 'https://www.nationalobserver.com/2023/03/27/news/mp-urges-feds-create-red-dress-alert-system-missing-women-girls-two-spirit', 'http://rabble.ca/blogs/bloggers/kairos-canada/2015/02/reaffirming-no-more-silence-on-world-day-social-justice', 'https://www.toronto.com/news/west-toronto-students-learn-about-indigenous-culture-truth-and-reconciliation-through-art/article_741c05c9-1e9f-5c02-b71f-ed1c1c8b6590.html']


bad_requests = ['http://www.durhamregion.com/news-story/6307872-more-than-1-200-missing-or-murdered-bennett/',
                'http://www.nationalobserver.com/2015/09/13/news/mulcair-promises-inquiry-missing-and-murdered-indigenous-women',
                'http://aptn.ca/news/2015/12/08/trudeau-government-releases-details-on-first-phase-of-national-inquiry-into-mmiw/',
                'http://nupge.ca/content/13068/national-inquiry-missing-and-murdered-indigenous-women-and-girls-officially-launched',
                'https://www.princegeorgecitizen.com/news/national-news/newsalert-inquiry-on-missing-murdered-indigenous-women-released-1.23842756',
                'http://www.parrysound.com/news-story/6309438-go-beyond-murdered-and-missing-tally-bennett/',
                'http://metronews.ca/news/canada/1336843/most-murdered-aboriginal-women-died-at-hands-of-other-aboriginals-rcmp/',
                'http://vietnamnews.vn/miscellany/279629/trudeau-announces-inquiry-into-missing-murdered-native-women.html',
                'http://sentinelrepublic.com/rcmp-to-release-update-on-missing-murdered-aboriginal-women/5184/',
                'http://thechronicleherald.ca/canada/1385025-government-to-launch-inquiry-into-missing-murdered-indigenous-women',
                'http://www.huffingtonpost.ca/2014/08/27/thomas-mulcair-native-aboriginal-inquiry_n_5722916.html',
                'http://www.cftktv.com/News/Story.aspx?ID=2189801',
                'https://cdanews.com/2015/12/canadas-federal-government-to-investigate-missingmurdered-aboriginal-women/',
                'http://aptn.ca/news/2015/02/26/two-decades-studies-undercut-ottawas-plan-combat-violence-indigenous-women-report/',
                'http://www.theeagle.com/news/world/canada-launches-inquiry-into-murdered-aboriginal-women/article_338eec61-f336-5715-b767-2d2f5262a339.html',
                'http://news.findlaw.com/apnews/a681280195334d44803f289a140a1dbf',
                'http://medicinehatnews.com/news/national-news/2017/05/15/missing-murdered-indigenous-women-inquiry-in-serious-trouble-advocates/',
                'http://www.turkishweekly.net/news/180944/no-national-inquiry-on-1-200-murdered-canadian-natives.html',
                'http://www.sfgate.com/world/article/Canada-to-open-inquiry-into-murdered-aboriginal-6684261.php',
                'http://jezebel.com/canadian-pm-justin-trudeau-launches-much-needed-inquiry-1747068382',
                'http://wawa-news.com/tag/aboriginal-news/',
                'https://www.uniradioinforma.com/noticias/internacional/692087/honran-a-4-mujeres-indigenas-asesinadas-en-canada.html',
                'https://www.torontotelegraph.com/news/266356233/how-indigenous-women-in-canada-heal-through-art',
                'http://aptn.ca/news/2015/03/26/rcmp-wont-release-new-information-murdered-missing-indigenous-women-cases/',
                'http://wkrg.com/ap/canada-to-launch-inquiry-into-murdered-aboriginal-women/',
                'http://www.newswire.ca/en/story/1559363/assembly-of-first-nations-national-chief-says-rcmp-update-on-missing-and-murdered-aboriginal-women-an-urgent-call-to-action-on-a-national-crisis',
                'http://www.princegeorgecitizen.com/news/world/feminism-missing-from-consultations-on-murdered-women-s-inquiry-advocates-1.2152916',
                'http://cjme.com/article/1310109/commissioner-resigns-inquiry-missing-and-murdered-indigenous-women',
                'http://www.chroniclejournal.com/news/national/premiers-commit-to-commission-recommendations-after-meeting-with-native-leaders/article_0d664cd4-8581-55b0-bd82-9b2735116110.html',
                'http://medicinehatnews.com/news/national-news/2015/12/11/lets-not-forget-she-was-a-child-police-charge-man-in-tina-fontaines-death/',
                'http://aptn.ca/news/2015/12/10/nine-years-ago-this-ojibway-woman-was-murdered-and-now-her-children-are-starting-to-ask-questions-2/',
                'http://theturtleislandnews.com/index.php/2016/02/15/3858/',
                'http://www.canada.com/news/metro/first+nations+families+speak+about+missing+loved+ones/11695262/story.html',
                'http://www.huffingtonpost.ca/2016/06/02/1-year-after-truth-and-reconciliation-report-not-seeing-change-yet_n_10255766.html',
                'http://www.calgarysun.com/2015/10/06/sisters-in-spirit-vigil-in-calgary-draws-hundreds-for-national-day-of-action-for-murdered-and-missing-aboriginal-women',
                'http://kstp.com/politics/lawmakers-may-study-violence-against-native-american-woman-/4868082/?cat=12681',
                'http://www.princegeorgecitizen.com/news/bc-news/five-things-to-know-about-the-inquiry-into-missing-murdered-indigenous-women-1.2315702',
                'https://www.brandonsun.com/national/breaking-news/tears-flow-at-thunder-bay-hearing-for-missing-and-murdered-indigenous-women-inquiry-461875373.html',
                'http://nupge.ca/content/12132/first-national-roundtable-missing-and-murdered-indigenous-women-and-girls-being-held',
                'http://www.nunatsiaqonline.ca/stories/article/65674nunavut_community_eyes_mmiwg_inquiry_to_bring_healing_closure/',
                'http://www.simcoe.com/news-story/6153595-orillia-event-gives-voice-to-missing-and-murdered-indigenous-women/',
                'https://www.theuknews.com/news/272457860/indigenous-organizations-describe-their-feature-projects-to-support-the-well-being-of-mmiwg-and-2slgbtqqia+-people-survivors-and-their-families',
                'http://www.voiceonline.com/federal-government-launches-inquiry-into-missing-and-murdered-indigenous-women-and-girls/',
                'http://www.wdio.com/news/thunder-bay-missing-and-murdered-indigenous-women-and-girls-inquiry/4695960/?cat=10335',
                'https://www.nationalobserver.com/2023/01/11/news/canada-appoints-adviser-help-create-role-overseeing-mmiwg2s-calls-justice',
                'https://www.niagarafallsreview.ca/ts/news/canada/2020/09/07/it-is-urgent-mmiwg-commissioner-calls-for-indigenous-bodies-to-oversee-police-in-canada.html',
                'http://www.chroniclejournal.com/news/national/inquiry-into-missing-and-murdered-indigenous-women-heads-to-nova/article_82ac17a0-5ddd-587b-aaab-65a78149b798.html',
                'https://www.toronto.com/opinion/ontario-regional-chief-glen-hare-offers-condolences-for-murdered-indigenous-women/article_afc110f9-c0c5-5a23-ac67-9c8c96f398cc.html',
                'https://energeticcity.ca/2021/06/05/i-am-so-so-sorry-mp-zimmer-to-vigil-organizer-on-mmiwg-comments/',
                'http://www.voiceonline.com/ontario-governments-statement-on-the-national-inquiry-into-missing-and-murdered-indigenous-women-and-girls/',
                'https://www.bramptonguardian.com/opinion/11-year-old-mohawk-girl-on-the-mmiwg2s-emergency/article_f5db80b7-7b6d-5b45-b34f-d0d929f70dba.html',
                'https://www.caledonenterprise.com/opinion/11-year-old-mohawk-girl-on-the-mmiwg2s-emergency/article_696eb4c3-76d1-521a-b1ed-281f20fce1b6.html',
                'http://www.thesuburban.com/life/lifestyles/stolen-sisters-looks-at-tragedy-of-missing-and-murdered-indigenous/article_a0605255-9426-5c30-ac21-578cc84f4e1c.html',
                'https://www.durhamregion.com/news-story/7979220-tears-at-missing-and-murdered-women-hearing/',
                'https://www.piquenewsmagazine.com/whistler/missing-murdered-women-inquiry-calls-for-justice-system-to-review-policies/Content?oid=13922144',
                'http://www.chroniclejournal.com/news/national/ontario-first-nations-chiefs-raise-funds-to-pay-for-inquiry/article_5f65bed0-9061-52b4-9831-e4bb1f974350.html',
                'http://www.piquenewsmagazine.com/whistler/remembrance-of-things-past/Content?oid=2804690',
                'https://www.piquenewsmagazine.com/whistler/bc-premier-promises-action-after-release-of-missing-women-inquiry-report/Content?oid=13930393',
                'https://www.stcatharinesstandard.ca/ts/news/canada/2023/04/26/saskatchewan-may-release-inquiry-into-prince-albert-police-after-serious-incidents.html',
                'http://www.brandonsun.com/national/breaking-news/five-stories-in-the-news-for-today-july-4-432415163.html',
                'http://www.thedailyobserver.ca/2017/12/06/a-dark-chapter-in-canadian-history-is-remembered',
                'https://www.chrisd.ca/2018/08/02/serena-mckay-teen-deadly-beating-manitoba-vsentence/',
                'http://www.chroniclejournal.com/opinion/editorials/inquiry-s-haste-is-overblown/article_be61899c-b586-11e5-8a67-9b55e3ac8cab.html',
                'https://www.nationalobserver.com/2023/03/29/news/ottawa-consultation-money-indigenous-resource-sharing',
                'https://www.thepeterboroughexaminer.com/ts/business/2023/03/28/budget-2023-feds-commit-consultation-money-for-indigenous-resource-sharing.html',
                'http://www.nationalobserver.com/2015/12/09/news/reflecting-power-murdered-and-missing-indigenous-women-inquiry',
                'http://medicinehatnews.com/news/national-news/2017/03/28/missing-murdered-women-inquiry-to-hold-first-hearing-may-29-in-whitehorse/',
                'https://www.theguardian.pe.ca/news/hundreds-gather-to-commemorate-murdered-women-in-montreal-pei-385283/',
                'https://www.niagarathisweek.com/news-story/8023706-inuk-woman-leaves-hospital-after-liver-failure/',
                'http://www.ourwindsor.ca/news-story/6169533-police-racism-must-be-addressed-in-inquiry-aboriginal-leaders-say/',
                'https://www.thechronicleherald.ca/opinion/regional-perspectives/letter-changing-the-way-police-do-business-is-imperative-for-the-indigenous-women-of-canada-465367/',
                'https://aptnnews.ca/2020/03/11/manitobas-project-devote-a-waste-of-time-when-it-comes-to-solving-murders-of-indigenous-women/',
                'https://medicinehatnews.com/news/national-news/2018/10/15/in-the-news-today-oct-15/',
                'http://markets.financialcontent.com/stocks/news/read?GUID=37717627',
                'http://www.townsvillebulletin.com.au/news/world/canada-to-open-inquiry-into-1200-murdered-or-missing-women/story-fnjbobeg-1227645156039',
                'http://heraldvoice.com/2015/12/11/feds-launch-phase-one-of-inquiry/',
                'http://www.cairnspost.com.au/news/world/canada-to-open-inquiry-into-1200-murdered-or-missing-women/story-fnjbobef-1227645156039',
                'http://www.metronews.ca/news/winnipeg/2017/06/18/manitobans-rally-for-missing-and-murdered-indigenous-males.html',
                'http://www.cjhk.ca/news/511771917/elder-calls-indigenous-youth-embrace-their-culture-way-help-stop-violence-against',
                'https://www.niagarathisweek.com/news-story/8077365-not-going-to-start-inquiry-over-trudeau/',
                'http://www.saultstar.com/2016/04/02/pk-fire-demands-inquiry-official',
                'http://rabble.ca/columnists/2019/06/never-forget-yes-there-was-genocide-why-dont-we-correct-wrong-now',
                'https://www.theifp.ca/news-story/8001574-potential-liver-donors-offer-to-help-inuk-woman/',
                'https://www.piquenewsmagazine.com/whistler/squamish-celebrity-lorne-cardinal-speaks-out-against-violence-against-indigenous-women-and-girls/Content?oid=13214085',
                'http://www.lillooetnews.net/tone-and-terms-of-missing-murdered-women-inquiry-will-be-critical-wally-oppal-1.2101457',
                'http://paherald.sk.ca/2019/06/03/this-is-genocide/',
                'http://www.chroniclejournal.com/opinion/columns/injustices-as-excuses-inquiry-must-look-at-violence-on-reserves/article_3cb979e6-6c64-11e6-90df-97cf0069fed2.html',
                'https://www.todayville.com/reddeer/younger-sister-of-tina-fontaine-now-missing-struggling-with-tragedy-family-2/',
                'http://www.worldjournal.com/3759033/article-%E5%8A%A0%E5%9C%8B%E5%A4%B1%E8%B9%A4%E3%80%81%E8%A2%AB%E6%AE%BA%E5%8E%9F%E4%BD%8F%E6%B0%91%E5%A5%B3%E6%80%A7-%E9%81%A0%E9%AB%98%E6%96%BC%E9%A0%90%E4%BC%B0/',
                'http://www.cjme.com/syn/653/229095/trial-to-begin-for-man-accused-of-killing-manitoba-teen-tina-fontaine/',
                'http://theturtleislandnews.com/index.php/2018/02/22/accused-death-tina-fontaine-not-guilty-murder/',
                'http://medicinehatnews.com/news/national-news/2015/03/25/winnipeg-police-should-have-protected-teen-later-found-dead-afn-chief/',
                'https://www.carlyleobserver.com/new-court-date-in-saskatchewan-s-fight-to-get-teepee-off-legislature-lawn-1.24185670',
                'https://www.chrisd.ca/2018/03/02/acquittal-accused-tina-fontaines-death-disappoints-winnipeg-police-chief/',
                'http://news.yahoo.com/trudeau-announces-inquiry-missing-murdered-native-women-155109794.html',
                'http://lethbridgeherald.com/news/national-news/2018/03/13/no-grounds-to-appeal-acquittal-in-tina-fontaine-murder-case-manitoba-crown/',
                'http://www.newhamburgindependent.ca/news-story/6500052-canadian-media-need-to-improve-coverage-of-indigenous-issues-report-says/',
                'http://theturtleislandnews.com/index.php/2015/12/15/man-accused-of-killing-teenager-tina-fontaine-waives-court-appearance/',
                'http://www.proceso.com.mx/?p=418435',
                'http://cjme.com/article/357415/man-accused-killing-teenager-tina-fontaine-scheduled-be-winnipeg-court',
                'http://lethbridgeherald.com/news/national-news/2015/03/25/winnipeg-police-should-have-kept-safe-teen-later-found-dead-afn-chief/',
                'http://cjme.com/article/357415/man-accused-killing-teenager-tina-fontaine-waives-court-appearance',
                'http://ckom.com/article/382224/man-accused-killing-tina-fontaine-had-long-history-violence-parole-board',
                'http://lethbridgeherald.com/news/national-news/2015/12/15/man-accused-of-killing-teenager-tina-fontaine-scheduled-to-be-in-winnipeg-court/',
                'http://www.parrysound.com/news-story/6194442-man-accused-of-killing-teen-to-be-in-court/',
                'http://wncn.com/ap/not-guilty-verdict-in-death-of-indigenous-teen-in-canada/',
                'https://www.chrisd.ca/2018/08/18/tina-fontaine-family-healing/',
                'http://medicinehatnews.com/news/national-news/2015/12/15/manitoba-childrens-advocate-now-free-to-review-tina-fontaine-case-minister/',
                'http://cjme.com/article/357415/manitoba-childrens-advocate-now-free-review-tina-fontaine-case-minister',
                'https://www.brandonsun.com/national/breaking-news/winnipeg-jury-to-begin-second-day-of-deliberations-in-tina-fontaine-murder-trial-474805893.html',
                'https://www.hamiltonnews.com/news-story/8148761-winnipeg-jury-deliberating-for-second-day-in-fontaine-murder-trial/',
                'http://lethbridgeherald.com/news/national-news/2018/03/13/no-grounds-crown-wont-appeal-acquittal-of-accused-in-tina-fontaine-case/',
                'http://volumeone.org/events/2017/03/14/224361_indigenizing_the_academy_spring_film_series',
                'http://theturtleislandnews.com/index.php/2015/12/09/national-chief-welcomes-governments-swift-action-on-national-inquiry/',
                'https://medicinehatnews.com/news/national-news/2019/06/03/explained-why-the-mmiwg-commission-invoked-canadian-genocide/',
                'http://aptn.ca/news/2016/08/03/meet-the-commissioners-that-will-lead-the-mmiw-national-inquiry/',
                'http://www.timminspress.com/2016/08/03/inquiry-into-murdered-missing-women-hailed',
                'https://theturtleislandnews.com/index.php/2022/01/18/indigenous-leaders-victims-families-call-for-urgent-action-as-mmiwg-report-filed-to-province/',
                'https://www.cfweradio.ca/news/alberta-news/alberta-avenue-community-league-working-to-turn-park-into-memorial-for-mmiwg/',
                'https://theturtleislandnews.com/index.php/2023/03/10/nuu-chah-nulth-continue-to-be-100-per-cent-affected-by-mmiwg-says-family-support-worker/',
                'https://www.bowenislandundercurrent.com/consider-safety-of-indigenous-women-in-resource-development-projects-mmiwg-inquiry-1.23845887',
                'http://www.theasianconnectionsnewspaper.com/statement-from-andrew-scheer-on-the-final-report-of-the-national-inquiry-into-missing-and-murdered-indigenous-women-and-girls/',
                'https://www.caledonenterprise.com/news/orphans-voice-of-the-missing-and-murdered-survivors-share-experience-of-loss-at-sharon-temple/article_c47414a0-81dd-5383-a8fb-36c2f9e62452.html',
                'https://aptnnews.ca/2020/02/07/one-of-a-kind-red-jingle-dress-cone-project-raising-awareness-of-mmiwg/',
                'https://montreal.ctvnews.ca/mmiwg-in-montreal-indigenous-activist-s-murder-leaves-deep-wounds-and-division-1.3842013',
                'https://www.ckom.com/syn/648/524487/now-the-real-work-begins-families-call-for-action-after-inquiry-report/',
                'https://www.thewesternstar.com/news/canada/indigenous-art-on-billboards-part-of-canadian-mmiwg-awareness-campaign-324940/',
                'http://boundarysentinel.com/news/attorney-general%E2%80%99s-statement-national-inquiry-42194',
                'http://thenelsondaily.com/news/attorney-general%E2%80%99s-statement-national-inquiry-42194',
                'http://cfnrfm.ca/national-inquiry-missing-murdered-indigenous-women-wants-two-year-extension/',
                'http://www.canada.com/life/huge+expectations+fear/11517488/story.html',
                'https://www.thebeaverton.com/2020/06/country-responsible-for-the-indian-act-chinese-head-tax-komagata-maru-africville-none-is-too-many-japanese-internment-camps-sixties-scoop-residential-schools-oka-crisis-and-mmiwg-declares-itsel/',
                'https://www.thestar.com/news/canada/2023/07/18/winnipeg-landfill-blockade-has-been-torn-down-amid-months-of-protest-why-manitoba-refuses-to-search-for-missing-indigenous-womens-remains.html',
                'http://www.brandonsun.com/lifestyles/breaking-news/indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered-missing-women-402145935.html',
                'http://www.brandonsun.com/national/breaking-news/rcmp-pitched-parallel-process-for-national-inquiry-into-missing-murdered-women-394850811.html',
                'http://www.brandonsun.com/national/breaking-news/canadian-tragedy-of-missing-murdered-indigenous-women-dates-back-decades-389103201.html',
                'http://www.brandonsun.com/national/breaking-news/indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered-missing-women-402145935.html',
                'http://www.brandonsun.com/national/breaking-news/missing-and-murdered-womens-inquiry-not-reaching-out-to-families-advocates-417989893.html',
                'http://www.brandonsun.com/national/breaking-news/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories-418002603.html',
                'https://www.thestar.com/news/canada/2020/12/02/lakefield-mans-painted-paddle-being-auctioned-in-support-of-mmiwg.html',
                'https://theturtleislandnews.com/index.php/2020/11/26/indigenous-groups-criticize-abc-series-big-sky-for-insensitivity-to-mmiwg/',
                'https://www.thepeterboroughexaminer.com/ts/entertainment/television/2020/11/26/indigenous-groups-criticize-abc-series-big-sky-for-insensitivity-to-mmiwg.html',
                'https://www.thestar.com/vancouver/2019/08/02/call-the-dang-thing-a-double-murder-rcmp-communication-breakdown-may-have-given-suspected-killers-a-head-start-critics-say.html',
                'https://www.durhamregion.com/news-story/10002641-delay-in-mmiwg-action-plan-sparks-dismay/',
                'http://www.931theborder.ca/news/260798971/cross-country-walk-mmiwg',
                'https://www.thestar.com/news/gta/2019/11/12/civilian-review-hears-missing-persons-cases-are-too-often-a-low-priority-for-police.html',
                'https://www.thestar.com/news/gta/2019/11/11/civilian-review-hears-missing-persons-cases-are-too-often-a-low-priority-for-police.html',
                'http://www.nunatsiaqonline.ca/stories/article/65674mmiwg_inquiry_makes_last-minute_visit_to_nunavut/',
                'https://theturtleislandnews.com/index.php/2021/06/08/ottawas-action-plan-for-the-natl-inquiry-on-mmiwg-is-fundamentally-flawed-says-nwac/',
                'http://www.timescolonist.com/rcmp-pitched-parallel-process-for-national-inquiry-into-missing-murdered-women-1.2351412',
                'http://thechronicleherald.ca/canada/1343977-six-stories-in-the-news-today-feb.-23',
                'http://www.princegeorgecitizen.com/news/rcmp-pitched-parallel-process-for-national-inquiry-into-missing-murdered-women-1.2351412',
                'http://medicinehatnews.com/news/national-news/2016/02/23/six-stories-in-the-news-today-feb-23/',
                'https://www.thestar.com/entertainment/stage/opinion/2018/12/18/robert-lepages-kanata-pisode-1-la-controverse-misses-the-mark.html',
                'http://www.cfra.com/NationalCP/Article.aspx?id=500869',
                'https://www.timminstoday.com/national-news/six-stories-in-the-news-today-feb-23-200826',
                'https://thetyee.ca/News/2023/02/13/Chelsea-Noelle-Tatyanna-Went-Missing/',
                'https://www.thestar.com/news/canada/2017/10/07/two-more-staffers-leave-national-inquiry-into-missing-and-murdered-indigenous-women-and-girls.html',
                'http://www.ckdr.net/news/350720264/kdsb-calling-mmiwg-hearings-treaty-3-territory',
                'https://www.huffingtonpost.ca/entry/indigenous-commissioner-transparency-mmiwg-report_ca_60285d04c5b6741597e279fc',
                'http://aptnnews.ca/2018/06/05/government-to-announce-fate-of-national-mmiwg-inquiry-tuesday-in-ottawa/',
                'https://www.trentonian.ca/news/national/police-chief-admits-some-fell-through-cracks-wants-expanded-collaboration-on-mmiwg/wcm/63c281e5-4363-479f-b9d1-e039c20fb30d',
                'https://paherald.sk.ca/2021/07/07/mmiwg-monument-unveiling-completes-two-years-of-collaboration/',
                'http://www.nunatsiaqonline.ca/stories/article/65674mmiwg_inquiry_cancels_nunavut_hearing/',
                'http://www.huffingtonpost.ca/2018/01/11/mmiwg-inquiry-loses-yet-another-executive-director_a_23331305/',
                'http://www.895thelake.ca/news/778247578/mmiwg-commissioner-defends-hearing-process',
                'http://www.huffingtonpost.ca/2017/10/30/loretta-saunders-family-testifies-at-mmiwg-inquiry-in-nova-scotia_a_23261327/',
                'http://aptn.ca/news/2016/07/20/leaked-document-appears-to-give-broad-powers-to-mmiw-national-inquiry/',
                'https://www.talkvietnam.com/tag/mmiwg-closing-ceremony/',
                'https://thetyee.ca/News/2023/02/15/Justin-Trudeau-Say-Their-Names/',
                'https://theturtleislandnews.com/index.php/2019/10/09/mmiwg-honoured-in-hamilton-city-embracing-reconciliation/',
                'https://www.coastreporter.net/report-about-violence-against-downtown-eastside-women-calls-for-change-1.23779576',
                'http://rabble.ca/blogs/bloggers/pamela-palmater/2016/08/if-it-doesnt-tackle-policing-trudeaus-national-inquiry-risks-',
                'http://www.durhamregion.com/news-story/5951675-b-c-tory-candidate-says-views-not-contradictory/',
                'http://ipolitics.ca/tag/aboriginal/',
                'https://lethbridgeherald.com/news/national-news/2020/12/10/yukon-releases-strategy-in-response-to-mmiw-national-inquiry-report/',
                'https://www.nationalobserver.com/2017/12/01/opinion/inability-focus-steers-troubled-mmiwg-inquiry-rocks',
                'https://thetyee.ca/News/2023/05/02/Youth-Fleeing-Welfare-Placements/',
                'http://www.reachfm.ca/christian-news/this-report-is-also-about-hope-national-inquiry-reveals-genocide-against-indigenous-women-and-girls-opportunity-to-do-better',
                'https://www.stalbertgazette.com/article/justice-column-needs-headline-20180224',
                'https://montreal.ctvnews.ca/indigenous-police-chief-calls-for-governments-to-implement-mmiwg-recommendations-1.4453787',
                'https://www.estevanmercury.ca/indigenous-police-chief-calls-for-governments-to-implement-mmiwg-recommendations-1.23846237',
                'http://theturtleislandnews.com/index.php/2019/06/06/indigenous-police-chief-calls-for-governments-to-implement-mmiwg-recommendations/',
                'https://aptnnews.ca/2019/12/05/after-undrip-mmiwg-commitments-attention-turns-to-throne-speech-for-hint-of-what-comes-next/',
                'https://www.princegeorgecitizen.com/news/national-news/indigenous-police-chief-calls-for-governments-to-implement-mmiwg-recommendations-1.23846237',
                'https://www.guelphmercury.com/news-story/7689004-national-inquiry-urged-to-hear-voices-of-indigenous-women-in-prison/',
                'https://www.therecord.com/news-story/7689004-national-inquiry-urged-to-hear-voices-of-indigenous-women-in-prison/',
                'https://www.hamiltonnews.com/news-story/7689004-national-inquiry-urged-to-hear-voices-of-indigenous-women-in-prison/',
                'http://medicinehatnews.com/news/national-news/2017/10/27/national-inquiry-urged-to-hear-voices-of-indigenous-women-in-prison/',
                'https://www.thespec.com/news-story/7689004-national-inquiry-urged-to-hear-voices-of-indigenous-women-in-prison/',
                'https://www.thereminder.ca/provincial-news/indigenous-leaders-say-they-do-not-accept-premiers-comments-on-landfill-search-7287649',
                'https://www.thompsoncitizen.net/manitoba-news/indigenous-leaders-say-they-do-not-accept-premiers-comments-on-landfill-search-7287649',
                'http://morningstaronline.co.uk/a-cadf-Canada-to-face-its-racism-demons',
                'https://lethbridgeherald.com/news/national-news/2024/05/22/first-nations-leader-says-little-change-for-womens-safety-since-pickton-murders/',
                'https://energeticcity.ca/2021/05/05/national-day-of-awareness-for-mmiwg2s-in-fsj/',
                'http://www.canada.com/news/first+nations+groups+urge+caution+before+governments+missingwomen/11505159/story.html',
                'http://www.timescolonist.com/we-need-to-get-this-right-missing-women-groups-urge-caution-before-inquiry-1.2106988',
                'http://medicinehatnews.com/news/national-news/2015/11/09/we-need-to-get-this-right-missingwomen-groups-urge-caution-before-inquiry/',
                'http://www.cfra.com/NationalCP/Article.aspx?id=486107',
                'https://www.kelownadailycourier.ca/news/national_news/article_2c717469-2ebc-599a-adc3-f1fa380c3efd.html',
                'https://www.durhamregion.com/news-story/9997522-pandemic-delays-national-plan-for-mmiwg/',
                'http://lethbridgeherald.com/news/local-news/2015/03/19/council-supports-missing-women-national-inquiry/',
                'http://www.fftimes.com/news/local/news/mmiwg-calls-action-highlighted-council',
                'https://www.capebretonpost.com/news/local/issues-caused-by-imposed-relocation-to-eskasoni-continue-to-reverberate-mmiwg-final-report-318131/',
                'https://www.niagarafallsreview.ca/news-story/9421238-indigenous-police-chief-calls-for-governments-to-implement-mmiwg-recommendations/',
                'http://www.canberratimes.com.au/lifestyle/life-and-relationships/real-life/i-visited-indigenous-women-in-canada--their-grief-was-all-too-familiar-20171120-gzozml.html',
                'https://www.cfweradio.ca/news/alberta-news/orange-and-red-haul-trucks-unveiled-to-raise-awareness-about-mmiwg-residential-schools/',
                'https://montreal.ctvnews.ca/recommendations-for-quebec-in-175-page-supplement-to-mmiwg-report-1.4450314',
                'http://www.kamloopsthisweek.com/tkemlups-councillor-kamloops-mp-weigh-in-on-national-inquiry-into-missing-and-murdered-women/',
                'http://www.chroniclejournal.com/news/local/full-moon-walkers-remember-lost-women/article_890d9602-9386-11e7-b63a-1fbac032cba0.html',
                'http://ipolitics.ca/tag/inuit/',
                'http://www.fftimes.com/news/global/national/13m-earmarked-mmiwg-projects',
                'http://cfnrfm.ca/mp-nathan-cullen-talks-mmiwg-inquiry-marijuana-legalization/',
                'https://aptnnews.ca/2020/01/03/poet-pulls-out-of-university-of-regina-lecture-after-mmiwg-controversy/',
                'http://cfnrfm.ca/group-says-mmiwg-inquiry-better-keep-families-informed/',
                'http://www.voiceonline.com/attorney-general-suzanne-anton-says-b-c-will-participate-fully-in-national-inquiry/',
                'https://www.piquenewsmagazine.com/whistler/indigenous-day-part-2-police-chief-says-vpd-values-its-relationship-with-indigenous-people/Content?oid=15514491',
                'https://www.tillsonburgnews.com/news/local-news/indigenous-leaders-applaud-mmiwg-report-say-it-cant-gather-dust/wcm/55c5189a-daf6-4574-90b3-b6774ab48481',
                'http://ipolitics.ca/author/chinta-puxley/',
                'http://www.kingscountynews.ca/News/Local/2016-10-23/article-4670068/Caribou-Legs-runs-through-the-Valley-for-the-sake-of-women%0D%0A&nbsp',
                'http://rabble.ca/news/2019/06/canada-has-long-history-ignoring-reports-mmiwg-inquiry',
                'http://rabble.ca/news/2015/02/harpers-record-refusal-act-violence-against-indigenous-women',
                'https://www.sudbury.com/national/canadian-tragedy-of-missing-murdered-indigenous-women-dates-back-decades-349376',
                'http://thechronicleherald.ca/canada/1385200-canadian-tragedy-of-missing-murdered-indigenous-women-dates-back-decades',
                'http://www.lillooetnews.net/canadian-tragedy-of-missing-murdered-indigenous-women-dates-back-decades-1.2315809',
                'http://www.squamishchief.com/canadian-tragedy-of-missing-murdered-indigenous-women-dates-back-decades-1.2315809',
                'http://www.princegeorgecitizen.com/news/national-news/canadian-tragedy-of-missing-murdered-indigenous-women-dates-back-decades-1.2315809',
                'http://lethbridgeherald.com/news/national-news/2016/08/03/canadian-tragedy-of-missing-murdered-indigenous-women-dates-back-decades/',
                'https://paherald.sk.ca/2017/07/28/charles-family-speaks-afn-convention-calls-mmiwg-commissioners-stay/',
                'https://www.torontotelegraph.com/news/274337192/government-of-canada-and-manitoba-to-announce-partnership-to-improve-the-response-to-the-national-crisis-of-mmiwg2s+',
                'http://www.skyvalleychronicle.com/FEATURE-NEWS/The-1200-Missing-and-Murdered-Indigenous-Women-and-Girls-Of-Canada-br-i-Government-launches-new-2-year-inquiry-i-2570786',
                'http://lethbridgeherald.com/news/lethbridge-news/2017/01/30/work-needed-to-follow-up-recommendations/',
                'http://www.sherwoodparknews.com/2017/03/02/exhibit-takes-the-bad-with-the-good',
                'https://www.stcatharinesstandard.ca/news-story/9879602-online-threats-racism-causing-fear-for-indigenous-women-mmiwg-commissioner-says/',
                'http://www.marketwatch.com/story/canada-jeopardizes-credible-footing-for-national-inquiry-by-delaying-on-eliminating-sex-discrimination-from-the-indian-act-2016-06-23',
                'http://www.northbaynipissing.com/news-story/6309438-go-beyond-murdered-and-missing-tally-bennett/',
                'https://www.thompsoncitizen.net/action-needed-after-report-on-murdered-and-missing-indigenous-women-families-1.23843428',
                'http://lethbridgeherald.com/news/national-news/2016/02/16/inquiry-must-go-beyond-tally-of-murdered-and-missing-indigenous-women-bennett/',
                'http://aptn.ca/news/2016/08/03/minister-of-indigenous-affairs-discusses-mmiw-national-inquiry/',
                'http://www.ameripublications.com/prime-minister-justin-trudeau-stresses-need-for-nation-to-nation-relationship/44607',
                'http://aptnnews.ca/2017/07/07/inquiry-commissioner-talks-about-state-of-national-mmiwg-inquiry/',
                'http://www.nunatsiaqonline.ca/stories/article/65674pauktuutit_and_three_other_inuit_orgs_to_be_official_voice_at_mmiwg_in/',
                'http://aptn.ca/news/2016/08/08/government-ignored-list-of-inuk-candidates-in-favour-of-its-own-for-national-inquiry-source/',
                'https://www.thestar.com/life/2017/03/12/toronto-tattoo-artist-inking-in-honour-of-missing-and-murdered-indigenous-women.html',
                'https://theturtleislandnews.com/index.php/2020/12/11/yukon-releases-strategy-in-response-to-mmiw-national-inquiry-report/',
                'https://www.vancourier.com/yukon-releases-strategy-in-response-to-mmiw-national-inquiry-report-1.24253120',
                'https://theturtleislandnews.com/index.php/2021/08/13/federal-government-announces-180m-for-mmiwg-programs-and-supports/',
                'http://thetyee.ca/News/2015/11/27/Justice-Minister-on-Sex-Work/',
                'http://www.timminspress.com/2015/11/12/angus-eager-to-take-on-new-role-as-indigenous-affairs-critic',
                'https://paherald.sk.ca/2019/06/29/police-chief-vows-to-address-national-inquiry-recommendations/',
                'https://lethbridgeherald.com/news/national-news/2019/06/03/now-the-real-work-begins-families-call-for-action-after-inquiry-report/',
                'https://www.thestar.com/news/canada/2016/11/20/indigenous-sexual-abuse-likely-to-dominate-inquiry-into-missing-murdered-women.html',
                'https://www.thestar.com/news/canada/2017/04/03/missing-murdered-womens-inquiry-frustrating-families-advocates-say.html',
                'http://www.winnipegfreepress.com/canada/head-of-missing-womens-inquiry-says-concrete-recommendations-needed-391924351.html',
                'http://www.winnipegfreepress.com/canada/missing-and-murdered-womens-inquiry-not-reaching-out-to-families-advocates-417989893.html',
                'http://www.newhamburgindependent.ca/opinion-story/6313793-indigenous-women-inquiry-may-backfire/',
                'http://ipolitics.ca/tag/afn/',
                'https://lethbridgeherald.com/news/lethbridge-news/2019/06/25/mmiwg-victims-are-not-just-a-statistic-they-have-names/',
                'http://rabble.ca/babble/canadian-politics/tracking-liberal-governments-record-keeping-promises-aka-trudeaumeter-2-thr',
                'http://www.ourwindsor.ca/opinion-story/6314488-expanding-the-inquiry-into-missing-and-murdered-indigenous-women-could-backfire-walkom/',
                'https://www.yahoo.com/lifestyle/shocking-little-done-native-women-150000805.html',
                'https://theturtleislandnews.com/index.php/2021/09/10/outrage-confusion-meets-appointment-of-non-indigenous-man-to-mmiwg-secretariat/',
                'http://medicinehatnews.com/news/national-news/2018/04/04/women-working-in-vancouver-sex-trade-were-seen-as-disposable-inquiry-hears/',
                'http://www.bclocalnews.com/news/389093101.html',
                'http://www.timescolonist.com/indigenous-minister-gives-b-c-first-nations-faith-in-missing-women-inquiry-1.2315685',
                'http://www.insidehalton.com/news-story/6341083-indigenous-families-want-action-from-roundtable/',
                'http://www.princegeorgecitizen.com/news/bc-news/indigenous-minister-gives-b-c-first-nations-faith-in-missing-women-inquiry-1.2315685',
                'https://www.cpac.ca/en/direct/cpac5/607593/native-womens-association-of-canada-on-mmiwg-inquirys-calls-for-justice/',
                'https://www.thestar.com/news/canada/2017/04/17/ontario-opens-family-support-centres-as-national-inquiry-into-murdered-and-missing-indigenous-women-and-girls-takes-a-pause.html',
                'https://medicinehatnews.com/news/southern-alberta-news/2019/06/14/action-needed-following-release-of-mmiwg-report-sacpa-told/',
                'https://theturtleislandnews.com/index.php/2022/12/18/reward-offered-to-help-locate-mmiwg/',
                'http://aptn.ca/news/2016/02/19/a-look-at-the-work-behind-the-mmiwg-pre-inquiry-consultations/',
                'http://www.nunatsiaqonline.ca/stories/article/65674mmiwg_inquiry_commissioners_vows_to_continue_despite_latest_resignatio/',
                'http://www.huffingtonpost.ca/2016/09/01/marion-buller-missing-murdered-indigenous-women_n_11815678.html',
                'https://www.carlyleobserver.com/explained-why-the-mmiwg-commission-invoked-canadian-genocide-1.23843783',
                'http://www.957thewolf.ca/item/1798-http-www-ctvnews-ca-canada-head-of-missing-women-s-inquiry-says-concrete-recommendations-needed-1-3053437',
                'https://www.thecentralvoice.ca/news/regional/update-national-inquiry-into-missing-and-murdered-indigenous-women-releases-final-report-317953/',
                'https://www.nationalobserver.com/2020/08/27/wetsueweten-matriarchs-sacred-berries-and-mmiwg',
                'http://www.huffingtonpost.ca/2015/06/15/probe-of-bc-urban-abori_n_7590352.html',
                'https://theturtleislandnews.com/index.php/2022/02/17/numbers-of-murdered-indigenous-women-climb-as-alberta-studies-provincial-mmiwg-report/',
                'http://www.ckdr.net/news/1431886655/metis-nation-upset-final-mmiwg-report',
                'https://www.thespec.com/news-story/9879602-online-threats-racism-causing-fear-for-indigenous-women-mmiwg-commissioner-says/',
                'https://www.thestar.com/news/canada/2020/03/08/online-threats-racism-causing-fear-for-indigenous-women-mmiwg-commissioner-says.html',
                'https://www.nsnews.com/online-threats-racism-causing-fear-for-indigenous-women-mmiwg-commissioner-1.24093172',
                'http://www.pentictonherald.ca/news/national_news/article_176efa61-7bd5-5151-b16b-6567f834f807.html',
                'https://pjmedia.com/news-and-politics/blame-bad-decisions-for-crime-not-structural-racism-and-colonialism/',
                'http://theturtleislandnews.com/index.php/2019/06/04/trudeau-accepts-inquiry-finding-of-genocide-but-says-focus-must-be-on-response/',
                'https://www.therecord.com/opinion-story/9427827-margaret-shkimba-genocide-is-the-right-word-to-describe-murdered-and-missing-indigenous-women-and-girls/',
                'http://www.nationalobserver.com/2015/12/08/news/ex-pickton-investigator-hopes-trudeau-government-learns-bcs-mmiw-failures',
                'http://www.chroniclejournal.com/news/national/missing-and-murdered-women-s-inquiry-not-reaching-out-to/article_00e65a75-dcad-5d1d-aa5e-f4c0a2de38d1.html',
                'https://medicinehatnews.com/news/national-news/2019/06/05/indigenous-police-chief-calls-for-governments-to-implement-mmiwg-recommendations/',
                'https://winnipeg.ctvnews.ca/winnipeg-students-collaborating-on-quilt-in-honour-of-mmiwg2s-1.5417848',
                'https://regina.ctvnews.ca/we-all-played-a-role-in-this-sask-police-respond-to-mmiwg-inquiry-1.4449764',
                'https://regina.ctvnews.ca/hard-when-someone-takes-your-family-members-mother-looks-to-mmiwg-inquiry-for-change-1.4449764',
                'https://www.895thelake.ca/2019/06/04/bob-nault-pledges-government-action-to-implement-mmiwg-recommendations/',
                'https://www.theuknews.com/news/269894645/two-years-after-the-mmiwg-report-targeted-work-must-move-urgently-ahead',
                'https://www.nationalobserver.com/2022/09/09/news/winnipeg-brewery-changing-label-out-respect-mmiwg-crisis',
                'http://www.ckdr.net/news/1270433395/kenora-mp-says-government-taking-action-mmiwg-final-report',
                'http://www.nunatsiaqonline.ca/stories/article/65674first_mmiwg_illustrates_need_for_more_time_says_inuit_organization/',
                'http://www.cranbrooktownsman.com/national/417991293.html',
                'https://www.thestar.com/news/canada/2020/06/02/federal-delay-of-mmiwg-action-plan-sparks-dismay-ahead-of-inquiry-anniversary.html',
                'http://www.nunatsiaqonline.ca/stories/article/65674ottawa_has_no_plans_to_add_inuk_commissioner_to_mmiwg_inquiry/',
                'https://theturtleislandnews.com/index.php/2020/06/02/federal-delay-of-mmiwg-action-plan-sparks-dismay-ahead-of-inquiry-anniversary/',
                'https://theturtleislandnews.com/index.php/2020/06/03/news-federal-delay-of-mmiwg-action-plan-sparks-dismay-ahead-of-inquiry-anniversary/',
                'https://www.nsnews.com/federal-delay-of-mmiwg-action-plan-sparks-dismay-ahead-of-inquiry-anniversary-1.24145128',
                'http://www.theguardian.pe.ca/news/regional/2017/4/3/missing-and-murdered-women-s-inquiry-not-reaching-out-to-families-advocates.html',
                'https://www.tbnewswatch.com/national-news/missing-and-murdered-womens-inquiry-not-reaching-out-to-families-advocates-579014',
                'http://www.roundhouseradio.com/news/2017/04/03/missing-and-murdered-womens-inquiry-not-reach',
                'http://www.thetelegram.com/news/regional/2017/4/3/missing-and-murdered-women-s-inquiry-not-reaching-out-to-families-advocates.html',
                'http://www.thewesternstar.com/news/regional/2017/4/3/missing-and-murdered-women-s-inquiry-not-reaching-out-to-families-advocates.html',
                'http://www.capebretonpost.com/news/regional/2017/4/3/missing-and-murdered-women-s-inquiry-not-reaching-out-to-families-advocates.html',
                'http://www.ngnews.ca/news/regional/2017/4/3/missing-and-murdered-women-s-inquiry-not-reaching-out-to-families-advocates.html',
                'https://www.massachusettssun.com/news/261390300/mmiwg-the-spirit-of-grassroots-justice-lives-at-the-heart-of-the-struggle',
                'http://theturtleislandnews.com/index.php/2017/04/03/missing-murdered-womens-inquiry-not-reaching-families-advocates/',
                'http://www.cheknews.ca/missing-and-murdered-womens-inquiry-not-reaching-out-to-families-advocates-2-297742/',
                'http://www.kelownadailycourier.ca/opinion/article_d14bec32-8f0d-11e9-a196-ef4a2df1d0ae.html',
                'http://theturtleislandnews.com/index.php/2017/07/12/mmiwg-need-open-doors-get-work-done/',
                'http://theturtleislandnews.com/index.php/2016/01/04/pre-inquiry-into-mmiwg-begins-this-week/',
                'http://cfnrfm.ca/national-inquiry-into-missing-and-murdered-indigenous-women-and-girls-in-vancouver/',
                'https://www.cjme.com/syn/653/573551/sask-professor-reacts-to-national-mmiwg-report/',
                'https://www.thetelegram.com/news/local/breaking-ground-on-mmiwg-commemorative-garden-in-corner-brook-494491/',
                'http://www.ckdr.net/news/1572960843/bob-nault-pledges-government-action-implement-mmiwg-recommendations',
                'https://goodmenproject.com/featured-content/true-or-false-jrrd/',
                'http://www.chrisd.ca/2017/04/03/missing-murdered-womens-inquiry-not-reaching-families-advocates/',
                'https://theturtleislandnews.com/index.php/2021/05/05/redress-day-bringing-awareness-to-mmiwg2s/',
                'http://www.qctonline.com/slc-students-learn-about-national-inquiry-missing-and-murdered-indigenous-women-and-girls',
                'http://www.voiceonline.com/coalition-calls-federal-plan-for-national-inquiry-too-vague/',
                'http://aptn.ca/news/2016/08/03/national-inquiry-budget-terms-of-reference-announced-during-opening-ceremony/',
                'https://www.chatelaine.com/opinion/as-an-indigenous-woman-i-was-triggered-by-the-mmiwg-report/',
                'http://www.nunatsiaqonline.ca/stories/article/65674mmiwg_stop_in_nunavut_delayed_by_a_week/',
                'http://www.nunatsiaqonline.ca/stories/article/65674mmiwg_inquiry_announces_first_nunavut_community_hearing/',
                'https://intercontinentalcry.org/canadas-mmiwg-report-spurs-debate-on-the-shifting-definitions-of-genocide/',
                'https://intercontinentalcry.org/national-mmiwg-inquiry-calls-for-transformative-change/',
                'http://www.cheknews.ca/national-inquiry-into-mmiwg-set-to-release-plans-in-vancouver-344284/',
                'http://www.cpac.ca/en/direct/cpac3/226544/mmiwg-inquiry-final-submissions-from-parties-with-standing-9/',
                'http://rabble.ca/blogs/bloggers/activist-toolkit-blog/2019/06/some-tools-help-implement-mmiwg-report-findings',
                'http://theturtleislandnews.com/index.php/2018/07/04/another-resignation-hits-mmiwg/',
                'http://www.ckdr.net/news/1083741031/final-week-testimony-mmiwg-hearings',
                'https://www.mexicostar.com/news/261355028/the-mmiwg-report-a-call-for-decolonizing-international-law-itself',
                'http://www.fftimes.com/news/local/news/council-hear-presentation-mmiwg-tonight',
                'http://www.nunatsiaqonline.ca/stories/article/65674mmiwg_inquiry_asks_for_patience_as_commission_prepares_for_spring_laun/',
                'http://energeticcity.ca/article/regional/2016/08/03/reaction-to-missing-and-murdered-women-national-inquiry',
                'https://www.chroniclejournal.com/news/national/trudeau-government-given-failing-grade-for-lack-of-action-plan-on-mmiwg/article_1261ff7c-9399-59bf-9b36-32a88e579a67.html',
                'https://www.thestar.com/news/canada/2020/06/03/trudeau-government-given-failing-grade-for-lack-of-action-plan-on-mmiwg.html',
                'https://www.simcoe.com/news-story/10013469-feds-get-a-fail-for-lack-of-mmiwg-action-plan/',
                'http://winnipeg.ctvnews.ca/national-mmiwg-inquiry-moving-forward-despite-continued-calls-for-a-reset-1.3560349',
                'http://www.nunatsiaqonline.ca/stories/article/65674national_indigenous_women_groups_call_for_inuk_rep_on_mmiwg/',
                'https://www.bowenislandundercurrent.com/trudeau-government-given-failing-grade-for-lack-of-action-plan-on-mmiwg-1.24145840',
                'http://www.nunatsiaqonline.ca/stories/article/65674waiting_on_photos_mmiwg_inquiry_visit_to_nunavut_raises_awareness_but_/',
                'https://www.895thelake.ca/2019/06/14/mmiwg-inquiry-calls-for-action/',
                'https://www.irishsun.com/news/261324769/canada-mmiwg-report-spurs-debate-on-the-shifting-definitions-of-genocide',
                'https://www.thestar.com/politics/federal/2019/06/05/international-group-of-american-countries-wants-to-investigate-mmiwg-genocide-findings.html',
                'https://theturtleislandnews.com/index.php/2022/01/10/justice-delayed-justice-denied-say-families-of-murdered-indigenous-women-as-alberta-announces-completion-of-final-mmiwg/',
                'http://www.nunatsiaqonline.ca/stories/article/65674national_womens_group_with_nunavut_member_calls_for_mmiwg_reset/',
                'https://www.thestar.com/news/city_hall/2020/02/19/toronto-must-do-more-to-respond-to-mmiwg-inquirys-calls-for-justice-city-report-says.html',
                'http://www.cpac.ca/en/direct/cpac4/252833/mmiwg-inquiry-commissioners-speak-with-media-about-final-report/',
                'http://www.cpac.ca/en/direct/cpac4/252837/mmiwg-inquiry-releases-its-final-report/',
                'http://aptn.ca/news/2016/08/03/commissioners-named-for-national-inquiry-into-missing-and-murdered-indigenous-women-and-girls/',
                'https://www.nationalobserver.com/2021/06/03/news/feds-mmiwg-report',
                'https://www.timescolonist.com/two-years-after-mmiwg-report-ottawa-releases-preliminary-national-plan-1.24326215',
                'http://www.895thelake.ca/news/1084355998/treaty-three-alliance-speak-mmiwg-national-inquiry',
                'https://www.thestar.com/news/canada/2020/06/03/one-year-ago-the-national-inquiry-into-missing-and-murdered-indigenous-women-issued-calls-for-justice-now-indigenous-people-are-issuing-a-call-to-action.html',
                'https://nit.com.au/mmiwg-inquiry-concludes-violence-against-women-and-girls-is-genocide/',
                'https://www.thepeterboroughexaminer.com/ts/news/canada/2020/06/03/one-year-ago-the-national-inquiry-into-missing-and-murdered-indigenous-women-issued-calls-for-justice-now-indigenous-people-are-issuing-a-call-to-action.html',
                'https://theturtleislandnews.com/index.php/2021/06/03/two-years-after-mmiwg-report-ottawa-releases-preliminary-national-plan/',
                'http://www.midnorthmonitor.com/2017/08/22/uuws-holds-demonstration-to-protest-lagging-national-inquiry-on-mmiw',
                'https://www.chatelaine.com/news/recommendations-mmiwg-final-report/',
                'https://www.cp24.com/news/michele-audette-commissioner-of-mmiwg-inquiry-among-five-named-to-senate-1.5528084',
                'https://medicinehatnews.com/news/southern-alberta-news/2019/06/08/mmiwg-report-still-leaves-many-questions-says-u-of-l-professor/',
                'https://www.nationalobserver.com/2021/07/30/news/michele-audette-commissioner-mmiwg-inquiry--five-senate-appointments',
                'https://www.brandonsun.com/national/breaking-news/indigenous-police-chief-calls-for-governments-to-implement-mmiwg-recommendations-510883522.html',
                'https://www.carlyleobserver.com/what-people-are-saying-about-the-mmiwg-national-action-plan-1.24326479',
                'https://theturtleislandnews.com/index.php/2021/06/03/what-people-are-saying-about-the-mmiwg-national-action-plan/',
                'https://www.timescolonist.com/what-people-are-saying-about-the-mmiwg-national-action-plan-1.24326479',
                'https://winnipeg.ctvnews.ca/advocates-and-families-await-action-and-answers-one-year-since-mmiwg-inquiry-1.4968407',
                'https://www.kamloopsthisweek.com/mich%C3%A8le-audette-commissioner-of-mmiwg-inquiry-among-five-named-to-senate-1.24347273',
                'https://thetyee.ca/News/2019/06/04/Survivors-React-Missing-Women-Inquiry-Colonial-Violence/',
                'https://www.nationalobserver.com/2021/09/29/news/lorelei-williams-says-canadians-must-believe-dark-truth-genocide',
                'http://www.voiceonline.com/b-c-supports-national-inquiry-family-liaison-unit-for-families/',
                'https://winnipeg.ctvnews.ca/deafening-silence-national-mmiwg-inquiry-organizers-want-more-to-be-done-from-government-1.4967196',
                'http://nupge.ca/content/12680/nupge-welcomes-national-inquiry-murdered-and-missing-indigenous-women-and-girls',
                'https://www.nationalobserver.com/2021/09/24/news/activists-mp-say-trudeau-failed-act-mmiwg-will-he-act-now',
                'https://www.kamloopsthisweek.com/indigenous-women-s-group-releases-own-plan-on-mmiwg-citing-toxic-federal-process-1.24325304',
                'https://www.chroniclejournal.com/news/national/violence-against-indigenous-women-during-covid-19-sparks-calls-for-mmiwg-plan/article_643389b5-4a4f-5351-8249-aac85082b8f3.html',
                'https://www.thestar.com/news/canada/2020/05/10/violence-against-indigenous-women-during-covid-19-sparks-calls-for-mmiwg-plan.html',
                'https://www.timescolonist.com/violence-against-indigenous-women-during-covid-19-sparks-calls-for-mmiwg-plan-1.24132749',
                'https://montreal.ctvnews.ca/montreal-s-native-women-s-shelter-gets-boost-in-federal-funding-for-mmiwg-project-1.5822690',
                'http://aptn.ca/news/2016/08/04/former-nwac-president-talks-sis-and-mmiw-national-inquiry/',
                'https://theturtleislandnews.com/index.php/2021/09/24/activists-mp-say-trudeau-failed-to-act-on-mmiwg-will-he-act-now/',
                'https://www.thereminder.ca/native-women-s-group-releasing-own-plan-on-mmiwg-citing-toxic-federal-process-1.24325304',
                'https://www.nationalobserver.com/2023/01/23/news/ndp-caucus-retreat-indigenous-housing-climate-mmiwg',
                'http://www.895thelake.ca/news/721981630/native-womens-group-concerned-lack-progress-mmiwg-inquiry',
                'https://www.895thelake.ca/2019/06/04/nan-supports-final-mmiwg-report/',
                'https://www.mix1037fm.com/2022/05/12/fort-mcmurrays-first-burgers-for-friendship-event-raises-over-2500-on-national-day-of-awareness-for-mmiwg2s/',
                'http://aptn.ca/news/2015/02/27/tears-flowed-families-missing-murdered-forced-select-roundtable-delegates/',
                'https://www.huffingtonpost.ca/entry/mmiwg-liberals-native-womens-association-canada_ca_5ed801dac5b6d4d798e23b75',
                'http://www.895thelake.ca/news/613929872/local-group-withdraws-support-mmiwg-inquiry',
                'https://theturtleislandnews.com/index.php/2023/01/09/its-not-just-about-my-sister-anymore-says-mmiwg-activist/',
                'https://www.todayville.com/jackhammers-fumes-turn-b-c-familys-panama-canal-cruise-into-construction-zone/',
                'http://www.nunatsiaqonline.ca/stories/article/65674pauktuutit_blasts_mmiwg_inquiry_for_lacking_inuit_representation/',
                'http://rabble.ca/blogs/bloggers/penney-kome/2016/08/killing-has-to-stop-national-inquiry-needs-broad-support-to-end-m',
                'http://www.895thelake.ca/news/768952117/hajdu-continues-offer-support-mmiwg-inquiry',
                'https://www.princegeorgecitizen.com/news/bc-news/marchers-gather-for-annual-b-c-event-to-honour-missing-murdered-women-1.24282145',
                'http://lethbridgeherald.com/news/local-news/2016/06/20/police-associations-one-step-closer-to-working-together/',
                'http://www.thewesternstar.com/news/regional/2017/4/3/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories.html',
                'http://www.timescolonist.com/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories-1.13909885',
                'http://www.ngnews.ca/news/regional/2017/4/3/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories.html',
                'http://www.trurodaily.com/news/regional/2017/4/3/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories.html',
                'http://www.capebretonpost.com/news/regional/2017/4/3/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories.html',
                'http://www.theguardian.pe.ca/news/regional/2017/4/3/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories.html',
                'http://www.journalpioneer.com/news/regional/2017/4/3/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories.html',
                'http://www.thetelegram.com/news/regional/2017/4/3/the-monday-news-briefing-an-at-a-glance-survey-of-some-top-stories.html',
                'https://aptnnews.ca/2019/05/30/prime-minister-key-cabinet-ministers-will-be-on-hand-to-accept-mmiwg-final-report-monday/',
                'https://www.ckom.com/syn/648/525494/world-has-positive-lesson-to-learn-after-mmiwg-inquiry-trudeau/',
                'https://www.kamloopsthisweek.com/news/trudeau-accepts-inquiry-finding-of-genocide-but-says-focus-must-be-on-response-1.23844821',
                'http://thechronicleherald.ca/novascotia/1477121-indigenous-murder-victims-family-seeks-more-help-from-national-inquiry',
                'http://www.ctvnews.ca/politics/families-call-for-hard-reset-of-mmiwg-inquiry-1.3537010',
                'https://www.bowenislandundercurrent.com/trudeau-accepts-inquiry-finding-of-genocide-but-says-focus-must-be-on-response-1.23844384',
                'https://www.vancourier.com/world-has-positive-lesson-to-learn-after-mmiwg-inquiry-trudeau-1.23846856',
                'https://www.theguardian.pe.ca/opinion/columnists/bonokoski-inquiry-into-mmiwg-claims-genocide-was-canadas-historic-goal-318053/',
                'http://theturtleislandnews.com/index.php/2015/12/09/chiefs-of-ontario-welcome-historic-federal-announcement-of-a-national-inquiry-into-missing-and-murdered-indigenous-women/',
                'http://wawa-news.com/2015/12/08/chiefs-of-ontario-welcome-historic-federal-announcement-of-national-inquiry-into-missing-murdered-indigenous-women/',
                'https://www.todayville.com/carbon-tax-revenue-could-go-straight-to-ontario-residents-mckenna/',
                'https://theturtleislandnews.com/index.php/2022/10/07/chair-of-albertas-mmiwg-premiers-council-confident-change-in-leadership-wont-kibosh-its-work/',
                'http://www.nunatsiaqonline.ca/stories/article/65674mmiwg_inquiry_reschedules_nunavut_hearing_for_2018/',
                'https://thetyee.ca/Analysis/2023/04/17/Better-Future-For-Downtown-Eastside/',
                'http://www.sentinelsource.com/news/national_world/trudeau-launches-investigation-into-the-deaths-and-disappearances-of-canada/article_60e199bc-ce49-5bde-9865-4156e76865ac.html',
                'http://nupge.ca/content/13299/nwac-releases-report-card-national-inquiry-missing-and-murdered-indigenous-women-and',
                'http://nismagazine.com/2018/02/24/rallies-are-happening-across-canada-calling-for-justice-for.html',
                'http://rabble.ca/babble/news-rest-us/on-national-inquiry-missing-and-murdered-indigenous-women',
                'https://www.pentictonherald.ca/news/national_news/article_ee2a09f3-d7ab-5250-a888-2df4f41f9c31.html',
                'http://ckom.com/article/594274/families-robert-picktons-victims-quickly-lobby-against-serial-killers-book',
                'http://www.tricitynews.com/former-top-cop-speaks-out-about-pickton-1.435071',
                'https://www.nationalobserver.com/2022/12/16/news/expert-search-landfill-womens-remains-succeed',
                'http://www.huewire.com/miscellaneous/notorious-serial-killer-s-book-penned-in-prison-hits-amazon/98633/',
                'https://www.princegeorgecitizen.com/news/national-news/family-of-serial-killer-s-victim-searches-downtown-eastside-after-teen-relative-goes-missing-1.23484098',
                'http://fait-religieux.com/2016/02/24/robert-william-pickton-book-stirs-outrage.html',
                'https://www.thereminder.ca/provincial-news/no-guarantees-but-expert-says-search-of-landfill-for-womens-remains-may-succeed-6256823',
                'http://www.insidehalton.com/news-story/5452470-5-reasons-the-roundtable-on-missing-and-murdered-aboriginal-women-matters/',
                'https://www.kenoraonline.com/articles/ontario-invests-in-rotary-peace-park-to-honour-mmiwg',
                'https://theturtleislandnews.com/index.php/2022/02/11/ignorance-of-councillors-alleged-racism-distract-from-work-on-mmiwg-file-in-northeast-alberta/',
                'https://aptnnews.ca/2019/06/27/un-report-highlights-systemic-violence-against-indigenous-women-supports-mmiwg-inquiry-findings/',
                'https://aptnnews.ca/2019/03/08/first-nation-counts-nearly-two-dozen-missing-and-murdered-women-rcmp-say-just-one/',
                'https://www.thestar.com/news/gta/2017/12/07/charity-celebrates-impact-of-five-everyday-political-citizens.html',
                'https://www.chatelaine.com/living/politics/5-ways-to-make-sex-work-safer/',
                'https://www.cjme.com/syn/653/561976/sask-polytechnic-marks-mmiwg-national-awareness-day/',
                'http://aptn.ca/news/2016/08/04/statement-on-the-mmiwg-inquiry-by-senator-murray-sinclair/',
                'https://www.cpac.ca/en/cpac-in-focus/mmiwg/', 'http://www.cpac.ca/en/cpac-in-focus/mmiwg/',
                'http://www.kamloopsthisweek.com/fashion-forward/',
                'https://www.richmond-news.com/indigenous-groups-criticize-abc-series-big-sky-for-insensitivity-to-mmiwg-1.24245903',
                'http://www.grandforksgazette.ca/national/402165725.html',
                'http://ckom.com/article/1128387/indigenous-sexual-abuse-likely-dominate-inquiry-murdered-missing-women',
                'http://thechronicleherald.ca/canada/1417290-indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered-missing-women',
                'https://www.tbnewswatch.com/national-news/indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered-missing-women-469033',
                'http://www.pqbnews.com/national/402165725.html',
                'http://www.cjme.com/syn/653/184464/mmiwg-inquiry-addresses-questions-on-after-care-for-families',
                'http://www.brantfordexpositor.ca/2017/07/16/six-nations-elected-council-calls-for-mmiwg-commissions-to-resign',
                'https://www.nationalobserver.com/2020/06/04/news/trudeau-government-gets-failing-grade-lack-action-plan-mmiwg',
                'https://www.piquenewsmagazine.com/whistler/trudeau-government-given-failing-grade-for-lack-of-action-plan-on-mmiwg/Content?oid=15457579',
                'https://www.fftimes.com/news/local/district/honouring-mmiwg-red-ribbon-campaign',
                'https://www.princegeorgecitizen.com/news/national-news/trudeau-government-given-failing-grade-for-lack-of-action-plan-on-mmiwg-1.24145840',
                'https://theturtleislandnews.com/index.php/2020/06/03/trudeau-government-given-failing-grade-for-lack-of-action-plan-on-mmiwg/',
                'https://www.princegeorgecitizen.com/trudeau-government-given-failing-grade-for-lack-of-action-plan-on-mmiwg-1.24145840',
                'http://www.southpeacenews.com/newsdesk/volume53/151007/news2.html',
                'https://www.niagarafallsreview.ca/news-story/10014120-one-year-ago-the-national-inquiry-into-missing-and-murdered-indigenous-women-issued-calls-for-justice-now-indigenous-people-are-issuing-a-call-to-action/',
                'http://www.nationalobserver.com/2016/03/10/news/calls-begin-national-inquiry-harper-damage',
                'http://ipolitics.ca/tag/metis/',
                'http://www.huffingtonpost.ca/2017/05/14/justice-delayed-victims-anxious-for-stalled-mmiw-inquiry-to-give-them-voice_n_16608090.html',
                'http://theturtleislandnews.com/index.php/2017/01/18/susan-vella-lead-commission-counsel-national-inquiry-missing-murdered-indigenous-woman-girls/',
                'http://thetyee.ca/News/2015/12/08/Missing-Women-Inquiry-Details/',
                'https://www.thestar.com/news/canada/2017/02/02/indigenous-boys-men-issues-to-be-added-to-national-inquiry-on-missing-and-murdered-women-girls.html',
                'http://www.cfra.com/NationalCP/Article.aspx?id=524039',
                'https://lethbridgeherald.com/news/national-news/2021/06/01/indigenous-womens-group-releases-own-plan-on-mmiwg-citing-toxic-federal-process/',
                'https://medicinehatnews.com/news/national-news/2021/06/03/moving-forward-on-mmiwg-findings-quebec-vaccination-rates-in-the-news-for-june-3/',
                'https://lethbridgeherald.com/news/national-news/2021/06/03/moving-forward-on-mmiwg-findings-quebec-vaccination-rates-in-the-news-for-june-3/',
                'https://lethbridgeherald.com/news/national-news/2019/06/06/world-has-positive-lesson-to-learn-after-mmiwg-inquiry-trudeau/',
                'https://medicinehatnews.com/news/national-news/2020/11/18/rcmp-needs-structural-changes-to-address-racism-mmiwg-commissioner/',
                'https://lethbridgeherald.com/news/national-news/2020/11/18/rcmp-needs-structural-changes-to-address-racism-mmiwg-commissioner/',
                'https://lethbridgeherald.com/entertainment/entertainment-news/2020/11/26/indigenous-groups-criticize-abc-series-big-sky-for-insensitivity-to-mmiwg/',
                'https://www.chroniclejournal.com/news/national/moving-forward-on-mmiwg-findings-quebec-vaccination-rates-in-the-news-for-june-3/article_0b1fa974-0a2e-5360-b482-fa5dfe377af5.html',
                'https://www.chatelaine.com/opinion/mmiwg-anniversary/',
                'https://www.thompsoncitizen.net/moving-forward-on-mmiwg-findings-quebec-vaccination-rates-in-the-news-for-june-3-1.24326228',
                'https://roundhouseradio.com/2017/07/07/indigenous-womens-inquiry-head-says-process-moving-at-lightning-speed/',
                'http://cfnrfm.ca/national-inquiry-missing-murdered-indigenous-women-girls-hold-first-hearing-may/',
                'https://ca.news.yahoo.com/indigenous-women-apos-inquiry-head-192115733.html',
                'http://aptnnews.ca/2018/05/15/mmiwg-quebec-city/',
                'https://www.thestar.com/news/canada/2019/06/26/mmiwg-commissioners-reconcile-canada-day-with-their-genocide-finding.html',
                'https://www.thestar.com/politics/political-opinion/2019/06/03/why-cant-we-use-the-word-genocide.html',
                'https://thetyee.ca/News/2022/08/29/Missing-Women-Salmon-River-Valley/',
                'https://www.ctvnews.ca/politics/un-high-commissioner-urges-redress-as-canada-responds-to-mmiwg-inquiry-1.4470388',
                'http://theturtleislandnews.com/index.php/2019/06/19/un-high-commissioner-urges-redress-as-canada-responds-to-mmiwg-inquiry-2/',
                'https://www.daily-times.com/story/news/local/navajo-nation/2019/05/26/navajo-nation-program-awareness-walk-brings-mmiwg-mmiw-issue-shiprock/1235988001/',
                'https://theturtleislandnews.com/index.php/2020/05/11/violence-against-indigenous-women-during-covid-19-sparks-calls-for-mmiwg-plan/',
                'http://www.wellandtribune.ca/2017/06/09/high-praise-from-six-nations-for-play-about-mmiwgs',
                'https://www.nationalobserver.com/2020/02/14/news/bc-protesters-remove-rail-blockade-honour-mmiwg',
                'https://www.thestar.com/opinion/contributors/2020/10/05/indigenous-women-must-lead-mmiwg-action-plan.html',
                'https://edmontonsun.com/news/news-news/police-consolidate-efforts-for-mmiwg-investigations/wcm/aa04c48b-4d8c-4e23-85c4-f0e5ec57c5cf',
                'http://theturtleislandnews.com/index.php/2017/05/10/long-journey-lorelei-williams/',
                'http://www.thetelegram.com/Canada---World/News/2016-11-20/article-4689837/Indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered,-missing-women/1',
                'http://www.lillooetnews.net/indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered-missing-women-1.2967661',
                'http://www.yorktonthisweek.com/indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered-missing-women-1.2967661',
                'http://www.princegeorgecitizen.com/news/national-news/indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered-missing-women-1.2967661',
                'http://www.princegeorgecitizen.com/news/indigenous-sexual-abuse-likely-to-dominate-inquiry-into-murdered-missing-women-1.2967661',
                'https://rock101.com/news/10005003/national-day-of-action-mmiwg-calls-for-justice/',
                'https://q107.com/news/5345518/mmiwg-report-final-findings-genocide/',
                'https://q107.com/news/5345789/national-inquiry-mmiwg-key-takeaways/']
wayback_urls = []
could_not_access_errors = []
could_not_access_urls = []
no_snapshot_urls = []

urls_to_check = retry_urls + more_bad_request

print("Checking", len(urls_to_check), "urls")


async def fetch_oldest_snapshot(url):
    """
    Fetches the oldest snapshot of the given URL.
    Returns a tuple (title, body_text) if successful, else None.
    """
    try:
        # Instantiate the CDX Server API
        cdx_api = WaybackMachineCDXServerAPI(url)

        # Retrieve snapshots
        snapshots = list(cdx_api.snapshots())

        # Check if we found any snapshots
        if snapshots:
            # Select the oldest snapshot
            oldest_snapshot = snapshots[0]
            # print(oldest_snapshot.timestamp)

            # Use the snapshot URL to fetch the page content
            # Construct the original URL for the oldest snapshot
            # Format: http://web.archive.org/web/<timestamp>/<original_url>
            original_url = f"http://web.archive.org/web/{oldest_snapshot.timestamp}/{oldest_snapshot.original}"
            print(original_url)
            with open('output_files/wayback_urls3.txt', 'a') as file:
                file.write(str(original_url) + '\n')
            return original_url
        else:
            no_snapshot_urls.append(url)
            print("no snapshot")
            return "no snapshot", f"No snapshots found for {url}"
    except Exception as e:
        could_not_access_urls.append(url)
        print({str(e)})
        with open('output_files/retry_wayback.txt', 'a') as file:
            file.write(str(url) + '\n')
        return None, f"Error fetching {url}: {str(e)}"


# Initialize lists to hold results
successful_fetches = []
failed_fetches = []


async def main(url_list):
    async with asyncio.Semaphore(10):  # Limit concurrency to 10
        tasks = [fetch_oldest_snapshot(url) for url in url_list]
        for task in asyncio.as_completed(tasks):
            result = await task
            if result[0] is not None and result[0] != "no snapshot":
                wayback_urls.append(result)
            else:
                could_not_access_errors.append(result)


start_time = datetime.datetime.now()

asyncio.run(main(urls_to_check))

end_time = datetime.datetime.now()

elapsed_time = end_time - start_time

print("Successful Fetches:")
print(wayback_urls)

print("\nFailed Fetches:")
print(could_not_access_errors)

print(f"Code took {elapsed_time}.")
