import asyncio
from playwright.async_api import async_playwright
import json
import datetime

# Initialize lists
bad_requests = []
could_not_access = []

# list of URLs
urls = [
    'https://www.cbc.ca/news/canada/manitoba/unidentified-woman-victim-jeremy-skibicki-first-degree-murder-winnipeg-1.6673214',
    'https://www.cbc.ca/news/canada/manitoba/red-dress-day-manitoba-mmiwg-1.6833440',
    'https://www.cbc.ca/news/canada/manitoba/sagkeeng-first-nation-unveils-mmiwg-monument-1.5233630',
    'https://www.cbc.ca/radio/unreserved/unreserved-mmiwg-crisis-1.6743886',
    'http://www.caledoniacourier.com/news/justice-rally-walk-to-end-violence-against-women/',
    'http://www.cbc.ca/news/canada/ottawa/maisy-odjick-s-mom-hails-announcement-of-inquiry-into-missing-and-murdered-indigenous-women-1.3356075',
    'http://www.cbc.ca/radio/thecurrent/the-current-for-june-28-2016-1.3655632/families-of-34-missing-or-dead-indigenous-women-demand-proper-investigations-1.3655656',
    'http://www.cbc.ca/news/canada/newfoundland-labrador/mmiwg-inquiry-day-2-labrador-1.4568323',
    'https://www.cbc.ca/news/canada/new-brunswick/a-mile-in-her-moccasins-red-shawl-healing-walk-1.4870550',
    'https://www.cbc.ca/news/canada/thunder-bay/families-advocates-continue-to-speak-out-for-mmiwg2s-in-thunder-bay-1.6748358',
    'http://www.cbc.ca/radio/thesundayedition/summer-reading-coalition-govt-essay-about-grief-aboriginal-women-stalin-s-daughter-1.3126226/no-more-silence-panel-discussion-on-murdered-and-missing-aboriginal-women-1.3126296',
    'https://www.norfolknews.ca/news-story/7608811-redress-a-call-to-action-on-missing-murdered-indigenous-women/',
    'http://www.cbc.ca/news/canada/thunder-bay/mmiw-inquiry-families-react-1.4200841',
    'http://www.cbc.ca/news/canada/ottawa/walking-with-our-sisters-memorial-for-murdered-and-missing-indigenous-women-drawing-crowds-in-ottawa-1.3260509',
    'http://www.cbc.ca/news/canada/nova-scotia/candlelight-vigils-honour-region-s-missing-murdered-indigenous-women-and-girls-1.4331052',
    'http://www.cbc.ca/news/canada/manitoba/manitoba-mmiw-inquiry-reaction-1.3355842',
    'https://www.cbc.ca/news/canada/manitoba/missing-murdered-indigenous-women-girls-calls-to-action-three-year-anniversary-1.6475627',
    'http://www.cbc.ca/news/indigenous/northern-ontario-families-mmiwg-inquiry-1.4558462',
    'http://www.cbc.ca/news/canada/calgary/missing-murdered-indigenous-women-alberta-1.3704500',
    'https://www.cbc.ca/news/canada/british-columbia/red-dress-day-bc-1.6833902',
    'http://www.cbc.ca/news/canada/prince-edward-island/pei-indigenous-murdered-native-council-1.3356330',
    'http://www.cbc.ca/news/politics/wherry-mmiw-inquiry-1.3706088',
    'https://www.cbc.ca/news/indigenous/mmiwg-vigil-parliament-hill-1.6606008',
    'http://canada.onlinenigeria.com/news/breaking-news/113867-missing-murdered-indigenous-women-an-election-issue-for-all-canadians-advocates-say.html',
    'https://www.cbc.ca/news/canada/new-brunswick/canada-failed-to-act-1.5160807',
    'https://www.cbc.ca/news/canada/north/mmiwg-inquiry-report-reaction-north-1.5160904',
    'https://www.terracestandard.com/news/indigenous-voices-finally-heard-with-final-mmiwg-report-says-northwest-b-c-advocate/',
    'http://www.cbc.ca/news/aboriginal/mmiw-5-cases-to-know-1.3452021',
    'https://www.cbc.ca/news/canada/manitoba/mmiwg-national-inquiry-child-welfare-1.4840825',
    'https://www.lacombeglobe.com/news/local-news/forgotten-moccasin-project-highlights-the-children-left-behind-by-missing-and-murdered-indigenous-women',
    'https://www.reddeeradvocate.com/news/troubled-inquiry-into-missing-murdered-indigenous-women-seeks-two-more-years/',
    'https://www.cbc.ca/news/canada/north/iqaluit-mmiw-hearings-begin-1.4815586',
    'http://www.cbc.ca/news/canada/prince-edward-island/vigil-aboriginal-women-missing-murdered-inquiry-1.3790786',
    'http://www.cbc.ca/news/canada/manitoba/sagkeeng-first-nation-has-most-unsolved-cases-of-missing-or-murdered-indigenous-women-1.3025156',
    'http://www.reddeeradvocate.com/news/tears-flow-at-thunder-bay-hearing-for-missing-and-murdered-indigenous-women-inquiry/',
    'http://thevillagessuntimes.com/2016/02/29/canada-officially-launches-national-inquiry-into-the-deaths/',
    'https://www.cbc.ca/news/canada/nova-scotia/canso-causeway-shut-down-chantel-moore-mmiwg-1.5688582',
    'https://www.cbc.ca/news/indigenous/mmiwg-highway-of-tears-afn-1.6748028',
    'http://bsccomment.com/2016/02/29/canadas-missing-or-killed-indigenous-women-higher-than.html',
    'https://www.cbc.ca/news/indigenous/mmiwg-closing-ceremony-cheryl-mcdonald-1.5152493',
    'https://www.cbc.ca/news/canada/edmonton/mmiw-edmonton-march-2019-1.5020708',
    'http://www.cbc.ca/news/canada/british-columbia/missing-murdered-indigenous-women-families-hopeful-1.3355760',
    'http://www.cbc.ca/news/canada/north/yukon-missing-murdered-women-inquiry-1.4070908',
    'http://www.cbc.ca/news/canada/thunder-bay/missing-murdered-indigenous-women-pre-inquiry-meetings-begin-in-thunder-bay-ont-1.3385621',
    'https://www.mix1037fm.com/2018/10/04/68735/', 'http://www.bbc.co.uk/news/world-us-canada-40063783',
    'http://www.vueweekly.com/deeper-inquiry-all-aboriginal-groups-must-have-a-voice-in-the-national-mmiwg-investigation/',
    'https://www.cbc.ca/news/indigenous/mmiwg-vigil-poorman-osoup-harrison-wilson-1.6604705',
    'http://www.tjcnewspaper.com/canada-to-open-inquiry-into-murdered-aboriginal-women-143661/',
    'http://www.cbc.ca/news/canada/north/mmiwg-yellowknife-opening-ceremony-1.4498815',
    'https://www.cbc.ca/news/canada/saskatoon/mmiw-yxecc-1.5230774',
    'https://www.cbc.ca/news/canada/new-brunswick/government-take-time-mmiwg-1.5161718',
    'http://www.cbc.ca/news/aboriginal/international-women-s-day-indigenous-women-still-not-equal-in-canada-1.2985100',
    'http://www.cbc.ca/news/canada/windsor/missing-murdered-indigenous-women-1.3707278',
    'http://www.cbc.ca/news/indigenous/mmiwg-inquiry-legal-team-announced-1.3940919',
    'http://www.cbc.ca/news/canada/montreal/iskweu-project-montreal-native-womens-shelter-1.4415605',
    'http://www.cbc.ca/news/canada/sudbury/sisters-spirit-sudbury-1.4331297',
    'https://www.cbc.ca/news/canada/thunder-bay/kenora-peace-park-mmiw-1.5730363',
    'https://www.cbc.ca/news/canada/manitoba/indigenous-writers-festival-thin-air-1.5293323',
    'https://www.cbc.ca/news/canada/manitoba/brandon-mmiwg-walk-awareness-1.6857198',
    'http://www.cbc.ca/news/canada/saskatchewan/case-closed-or-murder-questionable-circumstances-saskatchewan-missing-murdered-indigenous-women-1.3655091',
    'http://www.cbc.ca/news/canada/saskatoon/fsin-chief-upset-about-mmiw-inquiry-1.4192703',
    'http://www.manitoulin.ca/2016/10/12/birch-island-will-host-pre-inquiry-discussion-probe-missing-murdered-women/',
    'https://www.cbc.ca/news/canada/manitoba/opinion-winnipeg-homelessness-rfp-1.5186361',
    'https://www.cbc.ca/news/canada/manitoba/no-stone-left-unturned-mmiwg-families-skeptical-police-will-change-1.5160911',
    'http://www.vancitybuzz.com/2016/02/womens-memorial-march-vancouver-2016/',
    'http://www.cbc.ca/news/canada/british-columbia/mmiwg-announcement-1.4192573',
    'https://www.cbc.ca/news/canada/manitoba/jeremy-skibicki-winnipeg-serial-killings-advocates-1.6671736',
    'http://www.cbc.ca/news/canada/manitoba/cbc-mmiw-investigations-hillman-prize-1.3501398',
    'http://www.cbc.ca/news/indigenous/22-cases-added-to-cbc-s-missing-and-murdered-indigenous-women-database-1.3355012',
    'http://www.cbc.ca/news/canada/saskatoon/mmiwg-inquiry-saskatoon-first-day-1.4412791',
    'https://www.cbc.ca/news/canada/british-columbia/red-dresses-hang-across-b-c-in-a-call-for-justice-for-missing-and-murdered-indigenous-women-1.6015462',
    'http://www.cbc.ca/news/indigenous/mmiwg-faceless-dolls-disappear-1.4363768',
    'http://www.cbc.ca/news/canada/sudbury/unresolved-series-shelley-may-anderson-1.4368729',
    'https://www.cbc.ca/news/canada/montreal/2-7-million-suit-against-lanaudi%C3%A8re-health-authority-joyce-echaquan-1.6600656',
    'http://canada.onlinenigeria.com/news/breaking-news/133293-i-think-of-her-often-missing-woman-s-parents-worry-mmiw-inquiry-may-be-too-late.html',
    'https://www.cbc.ca/news/canada/manitoba/mmiwg-winnipeg-rally-national-emergency-1.6674143',
    'https://www.cbc.ca/radio/thehouse/midweek-podcast-tina-fontaine-s-legacy-and-indigenous-child-welfare-1.5056269',
    'https://www.nanaimobulletin.com/news/murdered-and-missing-honoured-at-stolen-sisters-memorial-march-in-b-c/',
    'https://www.cbc.ca/news/canada/manitoba/tina-fontaine-ninth-anniversary-memorial-1.6933494',
    'http://canada.onlinenigeria.com/news/breaking-news/133266-justice-for-families-requires-mmiw-inquiry-investigate-role-of-police-neil-macdonald.html',
    'https://www.cbc.ca/news/politics/rcmp-crcc-indigenous-woman-death-1.7199167',
    'http://www.cbc.ca/news/canada/british-columbia/i-ve-seen-the-destruction-spiritual-health-workers-aid-survivors-at-mmiwg-inquiry-1.4610065',
    'http://www.cbc.ca/news/indigenous/mmiwg-inquiry-brandi-morin-opinion-1.4224745',
    'http://www.cbc.ca/news/canada/windsor/%C3%A9cole-polytechnique-victims-remembered-in-windsor-1.3353618',
    'https://www.reddeeradvocate.com/news/holes-in-duvet-cover-under-scrutiny-in-death-of-teenaged-girl/',
    'http://www.cbc.ca/news/canada/manitoba/christine-wood-melinda-george-search-1.4036953',
    'http://www.cbc.ca/news/indigenous/mmiwg-inquiry-thunder-bay-quagon-mcginnis-mason-1.4432941',
    'http://www.cbc.ca/news/canada/british-columbia/burns-lake-reaction-sex-charges-1.4562092',
    'http://www.cbc.ca/news/canada/hamilton/mmiw-inquiry-1.3705622',
    'http://www.cbc.ca/news/canada/british-columbia/missing-and-murdered-women-solution-includes-grassroots-say-minister-advocate-1.2971077',
    'http://www.cbc.ca/news/politics/aboriginal-women-still-overrepresented-among-canada-s-missing-and-murdered-women-1.3120272',
    'http://blogs.vancouversun.com/2016/01/21/include-aboriginal-men-in-murdered-womens-inquiry-advocates/',
    'https://www.cbc.ca/news/canada/british-columbia/seamus-o-regan-national-action-plan-minister-veteran-affairs-missing-murdered-women-indigenous-1.5162718',
    'http://www.cbc.ca/radio/thecurrent/the-current-for-december-7-2016-1.3883544/she-was-aboriginal-she-had-an-addiction-sister-of-mmiw-says-family-had-to-push-police-1.3883698',
    'https://www.cbc.ca/news/canada/british-columbia/indigenous-leaders-criticize-mmiwg-action-plan-1.6051920',
    'http://www.cbc.ca/news/politics/politicians-first-nations-leaders-wrap-up-a-day-long-meeting-on-missing-and-murdered-aboriginal-women-1.2975001',
    'http://www.cbc.ca/news/politics/missing-and-murdered-indigenous-women-1st-phase-of-national-public-inquiry-outlined-today-1.3355492',
    'http://www.manitoulin.ca/2015/12/17/national-inquiry-will-show-racism-is-alive-and-well-in-canada-says-madahbee/',
    'https://www.cbc.ca/news/politics/indigenous-womens-shelters-103-million-1.6836034',
    'https://www.cbc.ca/news/canada/manitoba/landfill-search-reaction-1.6900780',
    'https://www.cbc.ca/news/politics/ndp-mp-leah-gazan-mmiwg-national-emergency-motion-1.6829298',
    'http://canada.onlinenigeria.com/news/breaking-news/119794-has-trudeau-kept-promise-on-missing-and-murdered-indigenous-women-inquiry.html',
    'https://www.cbc.ca/news/canada/nova-scotia/genocide-missing-and-murdered-indigenous-women-and-girls-1.5160670',
    'http://www.cbc.ca/news/politics/mmiw-trudeau-tracker-election-1.3460926',
    'http://www.westmanjournal.com/life-like-a-nightmare-since-daughter-s-fatal-beating-shared-online-mother-1.23347636',
    'http://www.cbc.ca/news/canada/manitoba/mmiwg-national-inquiry-winnipeg-oct-18-1.4361031',
    'http://www.cbc.ca/news/politics/mmiw-inquiry-launch-details-1.3704191',
    'https://www.cbc.ca/news/canada/nova-scotia/tanya-brooks-s-10th-anniversary-unsolved-murder-1.5131601',
    'https://www.cbc.ca/news/canada/manitoba/indigenous-women-winnipeg-homicide-profiles-2022-1.6673913',
    'http://www.cbc.ca/news/indigenous/mmiwg-whitehorse-first-hearings-wrap-1.4142419',
    'http://www.reddeeradvocate.com/news/more-shakeup-at-inquiry-into-murdered-and-missing-indigenous-women/',
    'http://www.cbc.ca/radio/thecurrent/friday-december-11-2015-1.3360502/listening-to-the-families-of-missing-and-murdered-indigenous-women-1.3360511',
    'https://www.cbc.ca/news/canada/manitoba/eishia-hudson-lawsuit-statement-of-claim-1.6296080',
    'https://www.cbc.ca/news/canada/british-columbia/murder-indigenous-women-rcmp-questions-1.6138214',
    'http://www.cbc.ca/news/canada/new-brunswick/vigil-mount-allison-brady-francis-tina-fontaine-colten-boushie-1.4585539',
    'http://www.cbc.ca/news/canada/obituary-marlene-bird-1.4419419',
    'http://www.cbc.ca/news/canada/manitoba/deadly-force-manitoba-indigenous-1.4607383',
    'http://blogs.windsorstar.com/opinion/brown-john-harper-ignores-deaths-of-native-women',
    'https://www.cbc.ca/news/canada/manitoba/gillingham-mayor-trialbyfire-1.6687834',
    'http://www.cbc.ca/news/canada/manitoba/raymond-cormier-secret-recordings-tina-fontaine-murder-trial-1.4534897',
    'http://www.cbc.ca/news/canada/saskatchewan/mmiw-inquiry-high-hopes-answers-1.3707529',
    'https://www.cbc.ca/news/canada/manitoba/winnipeg-landfill-blockades-mmiwg2s-1.6682270',
    'https://www.cbc.ca/news/canada/manitoba/brady-landfill-mmiwg-search-red-dresses-1.6714973',
    'https://www.cbc.ca/news/canada/manitoba/truth-reconciliation-day-michael-redhead-champagne-winnipeg-activist-1.6192349',
    'http://www.cbc.ca/news/canada/british-columbia/missing-women-s-inquiry-should-include-aboriginal-men-says-ernie-crey-1.3416631',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/rnc-chief-systemic-racism-rnc-response-1.6526523',
    'http://www.cbc.ca/news/canada/manitoba/unresolved-cases-of-missing-and-murdered-indigenous-women-1.3651516',
    'http://www.cbc.ca/news/canada/montreal/mmiwg-inquiry-resignation-1.4189791',
    'http://www.cbc.ca/news/canada/nova-scotia/missing-murdered-indigenous-women-girls-inquiry-snow-sculpture-1.3991641',
    'http://www.cbc.ca/news/indigenous/delilah-loretta-saunders-chamber-opera-andrew-noseworthy-mmiwg-1.4414857',
    'https://www.cbc.ca/news/canada/nova-scotia/marginalized-african-nova-scotian-indigenous-women-1.6806597',
    'https://www.cbc.ca/news/politics/rcmp-indigenous-women-remains-1.6900594',
    'https://www.mprnews.org/story/2018/04/16/lawmakers-may-study-violence-against-native-american-women',
    'http://www.cbc.ca/news/canada/manitoba/nahanni-fontaine-petition-tina-fontaine-1.4591161',
    'http://www.cbc.ca/news/aboriginal/indigenous-peoples-inquiry-analysis-1.3354869',
    'https://www.bbc.co.uk/news/world-us-canada-66317924',
    'https://www.cbc.ca/news/canada/manitoba/aboriginal-justice-inquiry-policing-1.6264154',
    'https://www.cbc.ca/news/canada/manitoba/winnipeg-police-chief-landfill-skibicki-victims-1.6672452',
    'https://www.brantnews.com/news-story/7765961-inquiry-calls-for-national-police-force/',
    'https://canadiandimension.com/articles/view/tracing-the-geography-of-canadas-racist-liquor-control-policies',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/first-voice-police-report-1.6521760',
    'http://www.cbc.ca/news/canada/thunder-bay/thunder-bay-police-mmiw-training-1.3758791',
    'http://www.cbc.ca/news/indigenous/quebec-police-investigation-val-dor-mmiw-1.4012189',
    'https://www.cbc.ca/news/canada/nova-scotia/nova-scotia-mass-shooting-inquiry-recommendations-1.6577128',
    'http://www.cbc.ca/news/canada/sudbury/unresolved-series-jane-louise-sutherland-1.4371324',
    'http://www.cbc.ca/news/canada/saskatoon/mother-of-kelly-goforth-welcomes-move-toward-a-national-inquiry-1.3314855',
    'https://www.theglobeandmail.com/politics/article-trudeau-vows-action-on-mmiwg-stops-short-of-calling-deaths-a-genocide/',
    'https://www.cbc.ca/news/politics/missing-murdered-indigenous-women-inquiry-statistics-1.5176756',
    'https://www.cbc.ca/news/canada/manitoba/human-rights-museum-landfill-search-support-1.6937655',
    'http://www.reddeeradvocate.com/news/families-walk-highway-of-tears-before-mmiw-hearing/',
    'http://www.cbc.ca/news/canada/cbc-missing-and-murdered-indigenous-women-caj-1.3605440',
    'https://www.cbc.ca/news/indigenous/mmiwg-inquiry-report-1.5158385',
    'https://www.cbc.ca/news/politics/missing-murdered-indigenous-people-filu-permanent-funding-1.6858029',
    'https://www.cbc.ca/news/canada/manitoba/rcmp-amc-newser-dec14-1.7059608',
    'http://www.reddeeradvocate.com/national-news/mmiw-inquiry-hears-slain-womans-family-angry-over-sex-trade-label/',
    'https://www.cbc.ca/news/canada/montreal/indigenous-families-have-a-right-to-the-truth-about-children-who-vanished-into-quebec-s-health-system-1.5834902',
    'http://www.cbc.ca/news/canada/thunder-bay/missing-murdered-inquiry-details-hajdu-1.3573412',
    'https://cfox.com/news/5345096/bc-indigenous-mmiwg-report/',
    'http://www.cbc.ca/news/indigenous/opinion-foster-care-system-path-to-mmiwg-1.4552407',
    'http://canada.onlinenigeria.com/montreal/116056-for-indigenous-people,-inquiries-can-fuel-change-%E2%80%94-but-only-if-governments-act.html',
    'http://www.cbc.ca/radio/thecurrent/the-current-for-february-23-2018-1.4547552/injustice-is-a-way-of-indigenous-life-say-advocates-dismayed-at-verdict-in-tina-fontaine-murder-trial-1.4548471',
    'https://www.cbc.ca/news/canada/british-columbia/jessica-patrick-smithers-bc-death-family-friends-memorial-1.5159144',
    'https://www.cbc.ca/news/canada/manitoba/jaeda-vanderwal-death-family-winnipeg-police-probe-1.5430286',
    'https://www.cbc.ca/news/canada/manitoba/indigenous-women-girls-deaths-landfill-action-needed-manitoba-1.6803494',
    'http://www.cbc.ca/news/canada/north/march-indigenous-youth-tina-fontaine-1.4558526',
    'http://www.cbc.ca/news/canada/manitoba/tina-fontaine-raymond-cormier-not-guilty-indigenous-leaders-1.4548159',
    'https://indiancountrytoday.com/news/canadian-minister-pope-needs-to-apologize-to-indigenous',
    'http://www.cbc.ca/news/indigenous/indigenous-youth-from-manitoba-attend-daugthers-of-the-vote-1.4013370',
    'http://www.cbc.ca/radio/asithappens/as-it-happens-friday-edition-1.4407258/indigenous-services-minister-says-ottawa-will-participate-in-innu-foster-care-inquiry-1.4407269',
    'http://nytlive.nytimes.com/womenintheworld/2016/04/07/new-minister-leads-effort-to-right-systemic-wrongs-against-canadas-indigenous-women/',
    'http://investmentunderground.com/2015/12/canada-announces-investigation-into-violence-against/',
    'https://www.cbc.ca/news/canada/manitoba/landfill-search-winnipeg-faq-1.6903343',
    'http://www.cbc.ca/news/aboriginal/ontario-first-nations-to-hold-inquiry-into-missing-murdered-indigenous-women-1.3220844',
    'http://www.cbc.ca/radio/thehouse/unacceptable-toxicity-at-the-rcmp-needs-to-be-cleaned-up-says-ralph-goodale-1.3453702/carolyn-bennett-shares-lessons-from-pre-inquiry-talks-on-murdered-missing-indigneous-women-1.3453703',
    'https://www.cbc.ca/news/canada/manitoba/skibicki-poll-cambria-harris-reaction-1.7115578',
    'http://www.cbc.ca/news/canada/newfoundland-labrador/nl-inuit-mmiw-1.3512896',
    'https://www.cbc.ca/news/indigenous/genocide-murdered-missing-indigenous-women-inquiry-report-1.5157580',
    'https://www.cbc.ca/news/canada/saskatchewan/national-day-of-action-mmiwg-1.6606126',
    'https://www.cbc.ca/news/canada/saskatoon/megan-gallagher-ashley-morin-mmiwg-saskatoon-north-battleford-1.6096488',
    'http://fait-religieux.com/2016/02/27/provinces-commit-to-help-inquiry-into-missing-murdered.html',
    'https://www.cbc.ca/news/canada/british-columbia/martial-arts-indigenous-women-1.6074679',
    'https://www.cbc.ca/news/canada/manitoba/brady-road-landfill-search-first-nations-woman-found-1.6801738',
    'https://www.theglobeandmail.com/canada/article-indigenous-women-girls-killed-at-rate-six-times-higher-than-non/',
    'https://www.cbc.ca/news/canada/manitoba/gazan-landfill-search-manitoba-un-1.6914593',
    'https://www.cbc.ca/news/canada/thunder-bay/headlines/deadly-force-indigenous-1.5680668',
    'https://www.cbc.ca/news/canada/edmonton/mmiwg-report-vigil-edmonton-1.5168576',
    'https://www.cbc.ca/news/canada/saskatchewan/sask-gov-indigenous-fall-session-1.4873764',
    'http://www.cbc.ca/news/indigenous/mmiwg-inquiry-indigenous-women-streets-1.4139814',
    'http://www.cbc.ca/news/canada/british-columbia/rcmp-civilian-watchdog-ian-mcphail-1.3986818',
    'https://www.cbc.ca/news/canada/nova-scotia/goldboro-lng-workcamp-pieridae-mi-kmaw-opposition-mmiwg-1.6047286',
    'http://www.cbc.ca/news/canada/hamilton/news/hamilton-debate-over-missing-murdered-indigenous-women-gets-heated-1.3261911',
    'http://www.cbc.ca/news/politics/politicians-first-nations-agree-to-another-roundtable-before-end-of-2016-1.2975001',
    'https://www.reddeeradvocate.com/news/acquittal-of-accused-in-tina-fontaines-death-disappoints-winnipeg-police-chief/',
    'https://winnipegsun.com/news/provincial/groundswell-of-support-show-governments-need-to-work-on-landfill-search-says-amc-grand-chief',
    'https://winnipegsun.com/news/provincial/southern-chiefs-urge-action-on-issue-of-mmiwg2s',
    'http://www.netnewsledger.com/2016/08/04/ontario-regional-chief-day-welcomes-long-overdue-mmiw-inquiry/',
    'http://www.netnewsledger.com/2017/12/18/nipissing-first-nation-chief-calls-mmiwg-head-commissioner-resign/',
    'https://www.theglobeandmail.com/opinion/article-the-mmiwg-inquiry-cannot-be-allowed-to-fail/',
    'https://nationalpost.com/news/canada/report-into-genocide-of-indigenous-women-calls-for-widespread-changes',
    'http://www.tjcnewspaper.com/canada-details-inquiry-on-missing-murdered-indigenous-women-152470/',
    'https://www.cbc.ca/news/canada/manitoba/amc-landfill-search-manitoba-prairie-green-1.7094507',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/innu-inquiry-natuashish-1.6817999',
    'https://www.cbc.ca/news/canada/montreal/families-of-missing-indigenous-children-answers-1.6437662',
    'https://www.cbc.ca/news/canada/manitoba/tessa-perry-homicide-familu-hilda-anderson-pyrz-1.6473000',
    'https://www.cbc.ca/news/politics/senator-rcmp-commissioner-resign-1.5612939',
    'https://www.cbc.ca/news/canada/manitoba/mmiwg-inquiry-winnipeg-visit-1.5171670',
    'http://www.cbc.ca/news/politics/first-nations-meeting-missing-murdered-indigenous-women-1.3357406',
    'http://www.manitoulin.ca/2017/02/08/grieving-father-murdered-woman-applauds-addition-men-national-inquiry/',
    'https://www.cbc.ca/news/canada/manitoba/brady-road-blockade-injunction-hearing-1.6905639',
    'https://www.cbc.ca/news/canada/manitoba/jeremy-skibicki-jury-judge-trial-1.7093471',
    'http://www.cbc.ca/news/canada/british-columbia/first-human-resources-policy-after-more-than-a-year-for-mmiwg-inquiry-1.4500439',
    'http://www.cbc.ca/news/canada/thunder-bay/what-a-missing-and-murdered-indigenous-women-inquiry-could-learn-from-an-inquest-in-thunder-bay-ont-1.3354621',
    'http://ckom.com/article/382224/man-accused-killing-tina-fontaine-had-long-history-violence-parole-board',
    'http://cjme.com/article/357415/man-accused-killing-teenager-tina-fontaine-waives-court-appearance',
    'https://www.cowichanvalleycitizen.com/news/final-day-of-public-hearings-for-missing-and-murdered-indigenous-women-and-girls/',
    'https://www.cbc.ca/news/canada/manitoba/jeremy-skibicki-opinion-poll-legal-aid-manitoba-1.7114419',
    'https://www.cbc.ca/news/canada/manitoba/jeremy-skibicki-pretrial-day-one-1.7019889',
    'https://www.manitoulin.ca/final-report-from-national-inquiry-into-missing-and-murdered-indigenous-women-and-girls-lists-231-calls-to-action/',
    'http://www.cbc.ca/news/canada/edmonton/missing-murdered-women-inquiry-1.4278744',
    'http://www.cbc.ca/news/indigenous/joey-knapaysweet-family-timmins-police-death-1.4553181',
    'https://www.cbc.ca/news/indigenous/mmiwg-list-cases-1.4856500',
    'https://www.cbc.ca/news/canada/new-brunswick/patty-musgrave-brady-francis-maurice-johnson-elsipogtog-indigenous-1.4968690',
    'http://www.cbc.ca/news/canada/manitoba/tina-fontaine-verdict-march-1.4548692',
    'http://www.cbc.ca/news/canada/north/pre-inquiry-mmiw-yellowknife-1.3394144',
    'https://q107.com/news/5346987/mmiwg-report-national-action-plan/',
    'http://www.tjcnewspaper.com/canada-launches-investigating-into-aboriginal-women-murder-cases-154607/',
    'https://www.cbc.ca/news/canada/manitoba/mmiwg-red-dress-day-2022-1.6443552',
    'http://www.cbc.ca/news/politics/missing-murdered-inquiry-1.3355492',
    'http://www.cbc.ca/news/indigenous/families-commemorate-first-official-mmiwg-day-in-manitoba-1.4329473',
    'http://www.cbc.ca/news/politics/mmiw-4000-hajdu-1.3450237',
    'https://www.cbc.ca/news/canada/manitoba/cambria-harris-fighting-mmiwg-1.6686515',
    'https://www.cbc.ca/news/canada/saskatchewan/missing-and-murdered-indigenous-women-and-girls-funding-1.6644281',
    'https://www.cbc.ca/news/canada/manitoba/manitoba-child-welfare-system-report-1.5946616',
    'https://www.cbc.ca/news/canada/manitoba/helen-betty-osborne-mmiwg-the-pas-manitoba-1.6248405',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/ann-lucas-murder-robert-hillroy-legge-parole-1.5298282',
    'https://www.cbc.ca/news/canada/manitoba/community-groups-response-anniversary-of-tina-fontaine-s-death-1.5249368',
    'https://www.cbc.ca/news/canada/manitoba/red-dress-day-mmiw-crisis-1.6833248',
    'https://www.cbc.ca/news/canada/nova-scotia/nova-scotia-native-women-s-association-zabrina-whitman-resilience-centre-1.6056511',
    'http://www.cbc.ca/news/canada/british-columbia/red-dress-project-vancouver-1.4334820',
    'https://www.cbc.ca/news/canada/thunder-bay/thunderbay-moosehidecampaign-mmiwg-1.6840363',
    'https://www.cbc.ca/news/politics/stefanovich-mmiwg-commemoration-kitigan-zibi-anishinabeg-1.5127976',
    'https://www.cbc.ca/news/canada/calgary/fatality-inquiry-tyla-chipaway-cab-driver-social-worker-1.4713195',
    'https://www.cbc.ca/news/canada/montreal/family-of-joyce-echaquan-announce-legal-action-1.5747675',
    'http://www.cbc.ca/news/canada/saskatchewan/women-walk-to-spread-awareness-missing-and-murdered-indigenous-women-1.3708041',
    'https://www.terracestandard.com/news/dozens-march-for-mmigw-at-third-annual-event-in-terrace/',
    'http://www.cbc.ca/news/canada/montreal/michele-audette-mmiw-inquiry-1.3705514',
    'https://www.westerlynews.ca/news/red-dresses-hanging-on-ubco-campus-address-nation-wide-issue/',
    'http://www.cbc.ca/news/canada/manitoba/mmiw-inquiry-questions-unresolved-1.3737771',
    'https://www.cbc.ca/news/canada/manitoba/families-mmiwg-trauma-informed-policing-1.6493484',
    'http://www.cbc.ca/news/canada/manitoba/tina-fontaine-ndinawe-raymond-cormier-trial-1.4521381',
    'http://www.cbc.ca/news/canada/saskatoon/walk-international-women-s-day-1.4571204',
    'https://www.cbc.ca/news/canada/manitoba/lawyer-harvey-pollock-obituary-1.6740928',
    'https://www.reddeeradvocate.com/news/red-dresses-a-reminder-of-missing-and-murdered-indigenous-women/',
    'https://www.cbc.ca/news/canada/new-brunswick/anns-eye-red-dress-day-fredericton-2024-1.7198100',
    'https://www.cbc.ca/news/canada/british-columbia/on-red-dress-day-coquitlam-students-activist-call-for-action-on-missing-and-murdered-indigenous-women-girls-1.6434106',
    'https://www.cbc.ca/news/canada/manitoba/drag-the-red-new-boat-1.5224263',
    'http://www.cbc.ca/news/canada/manitoba/raymond-cormier-tina-fontaine-trial-1.4507241',
    'https://www.cbc.ca/news/canada/manitoba/northern-first-nations-victims-intimate-partner-violence-1.5482430',
    'https://www.cloverdalereporter.com/news/lawyer-with-mmiw-inquiry-resigns-citing-government-interference/',
    'http://www.cbc.ca/news/canada/manitoba/dna-expert-raymond-cormier-tina-fontaine-trial-1.4513963',
    'https://www.cbc.ca/news/indigenous/red-handprints-mmiwg-1.5483955',
    'https://www.cbc.ca/news/canada/british-columbia/vancouver-police-under-scrutiny-deaths-indigenous-women-girls-1.6543555',
    'https://www.cbc.ca/news/indigenous/mmiwg-action-plan-update-1.6476685',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/housing-indigenous-women-1.6900014',
    'https://q107.com/news/4780016/bc-public-inquiry-money-laundering/',
    'http://www.cbc.ca/news2/interactives/stolen-sisters/',
    'https://www.caledoniacourier.com/news/vigil-downtown-kelowna-to-remember-missing-and-murdered-indigenous-women/',
    'http://www.vueweekly.com/amanda-rheaume-finds-inspiration-in-repetition-for-latest-album/',
    'https://www.cbc.ca/news/canada/warning-signs-intimate-partner-homicide-1.6269761',
    'http://www.cbc.ca/news/canada/montreal/quebec-aboriginal-community-inquiry-1.3356317',
    'https://www.cbc.ca/news/canada/edmonton/calls-to-justice-mmiwg-inquiry-marion-buller-1.5383410',
    'https://www.bclocalnews.com/news/kelowna-drums-up-attention-for-missing-and-murdered-indigenous-women/',
    'https://www.asianage.com/world/americas/040619/womens-rights-slipping-gender-equality-under-attack-canadian-pm-justin-trudeau.html',
    'http://www.cbc.ca/news/canada/manitoba/aboriginal-justice-inquiry-colten-boushie-gerald-stanley-jury-1.4532394',
    'https://www.cbc.ca/newsinteractives/features/jennifer-catcheway-family-15-years-too-long',
    'https://www.cbc.ca/news/canada/british-columbia/bc-first-nations-justice-council-1.7168998',
    'http://www.cbc.ca/news/politics/murdered-missing-inquiry-macdonald-1.3743744',
    'https://www.cbc.ca/news/canada/manitoba/red-dress-day-manitoba-mmiwg-1.6833440',
    'https://www.cbc.ca/news/canada/manitoba/sagkeeng-first-nation-unveils-mmiwg-monument-1.5233630',
    'https://www.cbc.ca/news/canada/thunder-bay/families-advocates-continue-to-speak-out-for-mmiwg2s-in-thunder-bay-1.6748358',
    'https://www.cbc.ca/news/canada/manitoba/unidentified-woman-victim-jeremy-skibicki-first-degree-murder-winnipeg-1.6673214',
    'https://www.cbc.ca/news/canada/new-brunswick/a-mile-in-her-moccasins-red-shawl-healing-walk-1.4870550',
    'https://www.cbc.ca/radio/unreserved/unreserved-mmiwg-crisis-1.6743886',
    'https://www.norfolknews.ca/news-story/7608811-redress-a-call-to-action-on-missing-murdered-indigenous-women/',
    'https://www.cbc.ca/news/canada/british-columbia/red-dress-day-bc-1.6833902',
    'https://www.cbc.ca/news/canada/manitoba/missing-murdered-indigenous-women-girls-calls-to-action-three-year-anniversary-1.6475627',
    'https://www.cbc.ca/news/indigenous/mmiwg-vigil-parliament-hill-1.6606008',
    'http://canada.onlinenigeria.com/news/breaking-news/113867-missing-murdered-indigenous-women-an-election-issue-for-all-canadians-advocates-say.html',
    'https://www.cbc.ca/news/canada/new-brunswick/canada-failed-to-act-1.5160807',
    'https://www.cbc.ca/news/canada/north/mmiwg-inquiry-report-reaction-north-1.5160904',
    'https://www.cbc.ca/news/canada/manitoba/mmiwg-national-inquiry-child-welfare-1.4840825',
    'https://www.lacombeglobe.com/news/local-news/forgotten-moccasin-project-highlights-the-children-left-behind-by-missing-and-murdered-indigenous-women',
    'https://www.cbc.ca/news/canada/north/iqaluit-mmiw-hearings-begin-1.4815586',
    'http://www.cbc.ca/news/canada/newfoundland-labrador/mmiwg-inquiry-day-2-labrador-1.4568323',
    'http://www.caledoniacourier.com/news/justice-rally-walk-to-end-violence-against-women/',
    'http://www.cbc.ca/news/canada/ottawa/maisy-odjick-s-mom-hails-announcement-of-inquiry-into-missing-and-murdered-indigenous-women-1.3356075',
    'http://www.cbc.ca/news/canada/thunder-bay/mmiw-inquiry-families-react-1.4200841',
    'http://www.cbc.ca/radio/thesundayedition/summer-reading-coalition-govt-essay-about-grief-aboriginal-women-stalin-s-daughter-1.3126226/no-more-silence-panel-discussion-on-murdered-and-missing-aboriginal-women-1.3126296',
    'http://www.cbc.ca/news/canada/ottawa/walking-with-our-sisters-memorial-for-murdered-and-missing-indigenous-women-drawing-crowds-in-ottawa-1.3260509',
    'http://www.cbc.ca/news/canada/nova-scotia/candlelight-vigils-honour-region-s-missing-murdered-indigenous-women-and-girls-1.4331052',
    'http://www.cbc.ca/news/canada/manitoba/manitoba-mmiw-inquiry-reaction-1.3355842',
    'https://www.cbc.ca/news/canada/nova-scotia/canso-causeway-shut-down-chantel-moore-mmiwg-1.5688582',
    'http://www.cbc.ca/news/indigenous/northern-ontario-families-mmiwg-inquiry-1.4558462',
    'http://www.cbc.ca/radio/thecurrent/the-current-for-june-28-2016-1.3655632/families-of-34-missing-or-dead-indigenous-women-demand-proper-investigations-1.3655656',
    'https://www.cbc.ca/news/indigenous/mmiwg-highway-of-tears-afn-1.6748028',
    'http://www.cbc.ca/news/canada/calgary/missing-murdered-indigenous-women-alberta-1.3704500',
    'http://thevillagessuntimes.com/2016/02/29/canada-officially-launches-national-inquiry-into-the-deaths/',
    'https://www.cbc.ca/news/indigenous/mmiwg-closing-ceremony-cheryl-mcdonald-1.5152493',
    'https://www.cbc.ca/news/canada/edmonton/mmiw-edmonton-march-2019-1.5020708',
    'http://www.cbc.ca/news/canada/prince-edward-island/pei-indigenous-murdered-native-council-1.3356330',
    'http://www.cbc.ca/news/politics/wherry-mmiw-inquiry-1.3706088',
    'https://www.cbc.ca/news/indigenous/mmiwg-vigil-poorman-osoup-harrison-wilson-1.6604705',
    'http://www.vueweekly.com/deeper-inquiry-all-aboriginal-groups-must-have-a-voice-in-the-national-mmiwg-investigation/',
    'http://www.tjcnewspaper.com/canada-to-open-inquiry-into-murdered-aboriginal-women-143661/',
    'https://www.cbc.ca/news/canada/saskatoon/mmiw-yxecc-1.5230774',
    'https://www.cbc.ca/news/canada/new-brunswick/government-take-time-mmiwg-1.5161718',
    'http://www.cbc.ca/news/aboriginal/mmiw-5-cases-to-know-1.3452021',
    'http://bsccomment.com/2016/02/29/canadas-missing-or-killed-indigenous-women-higher-than.html',
    'https://www.cbc.ca/news/canada/thunder-bay/kenora-peace-park-mmiw-1.5730363',
    'https://www.cbc.ca/news/canada/manitoba/indigenous-writers-festival-thin-air-1.5293323',
    'https://www.cbc.ca/news/canada/manitoba/brandon-mmiwg-walk-awareness-1.6857198',
    'http://www.cbc.ca/news/canada/prince-edward-island/vigil-aboriginal-women-missing-murdered-inquiry-1.3790786',
    'http://www.manitoulin.ca/2016/10/12/birch-island-will-host-pre-inquiry-discussion-probe-missing-murdered-women/',
    'https://www.cbc.ca/news/canada/manitoba/opinion-winnipeg-homelessness-rfp-1.5186361',
    'https://www.cbc.ca/news/canada/manitoba/no-stone-left-unturned-mmiwg-families-skeptical-police-will-change-1.5160911',
    'http://www.vancitybuzz.com/2016/02/womens-memorial-march-vancouver-2016/',
    'https://www.mix1037fm.com/2018/10/04/68735/',
    'https://www.cbc.ca/news/canada/manitoba/jeremy-skibicki-winnipeg-serial-killings-advocates-1.6671736',
    'http://www.cbc.ca/news/canada/manitoba/sagkeeng-first-nation-has-most-unsolved-cases-of-missing-or-murdered-indigenous-women-1.3025156',
    'http://www.reddeeradvocate.com/news/tears-flow-at-thunder-bay-hearing-for-missing-and-murdered-indigenous-women-inquiry/',
    'http://www.cbc.ca/news/canada/north/yukon-missing-murdered-women-inquiry-1.4070908',
    'http://www.cbc.ca/news/canada/thunder-bay/missing-murdered-indigenous-women-pre-inquiry-meetings-begin-in-thunder-bay-ont-1.3385621',
    'http://www.cbc.ca/news/canada/british-columbia/missing-murdered-indigenous-women-families-hopeful-1.3355760',
    'http://www.cbc.ca/news/canada/north/mmiwg-yellowknife-opening-ceremony-1.4498815',
    'https://www.cbc.ca/news/canada/british-columbia/red-dresses-hang-across-b-c-in-a-call-for-justice-for-missing-and-murdered-indigenous-women-1.6015462',
    'https://www.cbc.ca/news/canada/montreal/2-7-million-suit-against-lanaudi%C3%A8re-health-authority-joyce-echaquan-1.6600656',
    'https://www.cbc.ca/news/canada/manitoba/mmiwg-winnipeg-rally-national-emergency-1.6674143',
    'http://www.cbc.ca/news/aboriginal/international-women-s-day-indigenous-women-still-not-equal-in-canada-1.2985100',
    'http://canada.onlinenigeria.com/news/breaking-news/133293-i-think-of-her-often-missing-woman-s-parents-worry-mmiw-inquiry-may-be-too-late.html',
    'http://www.cbc.ca/news/indigenous/mmiwg-inquiry-legal-team-announced-1.3940919',
    'http://www.cbc.ca/news/canada/windsor/missing-murdered-indigenous-women-1.3707278',
    'http://www.cbc.ca/news/canada/montreal/iskweu-project-montreal-native-womens-shelter-1.4415605',
    'http://www.cbc.ca/news/canada/sudbury/sisters-spirit-sudbury-1.4331297',
    'https://www.cbc.ca/radio/thehouse/midweek-podcast-tina-fontaine-s-legacy-and-indigenous-child-welfare-1.5056269',
    'https://www.cbc.ca/news/canada/manitoba/tina-fontaine-ninth-anniversary-memorial-1.6933494',
    'http://www.cbc.ca/news/canada/saskatchewan/case-closed-or-murder-questionable-circumstances-saskatchewan-missing-murdered-indigenous-women-1.3655091',
    'https://www.cbc.ca/news/politics/rcmp-crcc-indigenous-woman-death-1.7199167',
    'http://www.cbc.ca/news/canada/saskatoon/fsin-chief-upset-about-mmiw-inquiry-1.4192703',
    'http://canada.onlinenigeria.com/news/breaking-news/133266-justice-for-families-requires-mmiw-inquiry-investigate-role-of-police-neil-macdonald.html',
    'http://www.cbc.ca/news/canada/british-columbia/mmiwg-announcement-1.4192573',
    'http://www.cbc.ca/news/canada/manitoba/cbc-mmiw-investigations-hillman-prize-1.3501398',
    'http://blogs.vancouversun.com/2016/01/21/include-aboriginal-men-in-murdered-womens-inquiry-advocates/',
    'https://www.cbc.ca/news/canada/british-columbia/seamus-o-regan-national-action-plan-minister-veteran-affairs-missing-murdered-women-indigenous-1.5162718',
    'http://www.cbc.ca/news/canada/saskatoon/mmiwg-inquiry-saskatoon-first-day-1.4412791',
    'http://www.cbc.ca/news/indigenous/22-cases-added-to-cbc-s-missing-and-murdered-indigenous-women-database-1.3355012',
    'http://www.cbc.ca/news/canada/sudbury/unresolved-series-shelley-may-anderson-1.4368729',
    'http://www.cbc.ca/news/indigenous/mmiwg-faceless-dolls-disappear-1.4363768',
    'https://www.cbc.ca/news/canada/british-columbia/indigenous-leaders-criticize-mmiwg-action-plan-1.6051920',
    'http://www.manitoulin.ca/2015/12/17/national-inquiry-will-show-racism-is-alive-and-well-in-canada-says-madahbee/',
    'https://www.cbc.ca/news/politics/indigenous-womens-shelters-103-million-1.6836034',
    'https://www.cbc.ca/news/canada/manitoba/landfill-search-reaction-1.6900780',
    'https://www.cbc.ca/news/politics/ndp-mp-leah-gazan-mmiwg-national-emergency-motion-1.6829298',
    'https://www.cbc.ca/news/canada/nova-scotia/genocide-missing-and-murdered-indigenous-women-and-girls-1.5160670',
    'http://canada.onlinenigeria.com/news/breaking-news/119794-has-trudeau-kept-promise-on-missing-and-murdered-indigenous-women-inquiry.html',
    'http://www.cbc.ca/news/canada/british-columbia/i-ve-seen-the-destruction-spiritual-health-workers-aid-survivors-at-mmiwg-inquiry-1.4610065',
    'http://www.cbc.ca/news/indigenous/mmiwg-inquiry-brandi-morin-opinion-1.4224745',
    'https://www.reddeeradvocate.com/news/holes-in-duvet-cover-under-scrutiny-in-death-of-teenaged-girl/',
    'http://www.cbc.ca/news/canada/windsor/%C3%A9cole-polytechnique-victims-remembered-in-windsor-1.3353618',
    'http://www.cbc.ca/news/canada/manitoba/christine-wood-melinda-george-search-1.4036953',
    'http://www.cbc.ca/news/indigenous/mmiwg-inquiry-thunder-bay-quagon-mcginnis-mason-1.4432941',
    'http://www.cbc.ca/news/canada/british-columbia/burns-lake-reaction-sex-charges-1.4562092',
    'http://www.cbc.ca/news/canada/hamilton/mmiw-inquiry-1.3705622',
    'https://www.cbc.ca/news/canada/nova-scotia/tanya-brooks-s-10th-anniversary-unsolved-murder-1.5131601',
    'https://www.cbc.ca/news/canada/manitoba/indigenous-women-winnipeg-homicide-profiles-2022-1.6673913',
    'https://www.cbc.ca/news/canada/manitoba/eishia-hudson-lawsuit-statement-of-claim-1.6296080',
    'https://www.cbc.ca/news/canada/british-columbia/murder-indigenous-women-rcmp-questions-1.6138214',
    'http://www.cbc.ca/news/canada/british-columbia/missing-and-murdered-women-solution-includes-grassroots-say-minister-advocate-1.2971077',
    'http://blogs.windsorstar.com/opinion/brown-john-harper-ignores-deaths-of-native-women',
    'https://www.cbc.ca/news/canada/manitoba/gillingham-mayor-trialbyfire-1.6687834',
    'http://www.westmanjournal.com/life-like-a-nightmare-since-daughter-s-fatal-beating-shared-online-mother-1.23347636',
    'https://www.cbc.ca/news/canada/manitoba/winnipeg-landfill-blockades-mmiwg2s-1.6682270',
    'https://www.cbc.ca/news/canada/manitoba/brady-landfill-mmiwg-search-red-dresses-1.6714973',
    'https://www.cbc.ca/news/canada/manitoba/truth-reconciliation-day-michael-redhead-champagne-winnipeg-activist-1.6192349',
    'http://www.cbc.ca/news/politics/aboriginal-women-still-overrepresented-among-canada-s-missing-and-murdered-women-1.3120272',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/rnc-chief-systemic-racism-rnc-response-1.6526523',
    'http://www.cbc.ca/radio/thecurrent/the-current-for-december-7-2016-1.3883544/she-was-aboriginal-she-had-an-addiction-sister-of-mmiw-says-family-had-to-push-police-1.3883698',
    'http://www.cbc.ca/news/politics/politicians-first-nations-leaders-wrap-up-a-day-long-meeting-on-missing-and-murdered-aboriginal-women-1.2975001',
    'http://www.cbc.ca/news/politics/missing-and-murdered-indigenous-women-1st-phase-of-national-public-inquiry-outlined-today-1.3355492',
    'http://www.cbc.ca/news/politics/mmiw-trudeau-tracker-election-1.3460926',
    'https://www.cbc.ca/news/canada/nova-scotia/marginalized-african-nova-scotian-indigenous-women-1.6806597',
    'https://www.cbc.ca/news/politics/rcmp-indigenous-women-remains-1.6900594',
    'http://www.cbc.ca/news/canada/manitoba/mmiwg-national-inquiry-winnipeg-oct-18-1.4361031',
    'http://www.cbc.ca/news/indigenous/mmiwg-whitehorse-first-hearings-wrap-1.4142419',
    'http://www.cbc.ca/radio/thecurrent/friday-december-11-2015-1.3360502/listening-to-the-families-of-missing-and-murdered-indigenous-women-1.3360511',
    'http://www.cbc.ca/news/politics/mmiw-inquiry-launch-details-1.3704191',
    'http://www.cbc.ca/news/canada/new-brunswick/vigil-mount-allison-brady-francis-tina-fontaine-colten-boushie-1.4585539',
    'https://www.cbc.ca/news/canada/manitoba/aboriginal-justice-inquiry-policing-1.6264154',
    'http://www.cbc.ca/news/canada/obituary-marlene-bird-1.4419419',
    'http://www.cbc.ca/news/canada/manitoba/deadly-force-manitoba-indigenous-1.4607383',
    'https://www.cbc.ca/news/canada/manitoba/winnipeg-police-chief-landfill-skibicki-victims-1.6672452',
    'https://www.brantnews.com/news-story/7765961-inquiry-calls-for-national-police-force/',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/first-voice-police-report-1.6521760',
    'https://www.cbc.ca/news/canada/nova-scotia/nova-scotia-mass-shooting-inquiry-recommendations-1.6577128',
    'http://www.cbc.ca/news/canada/manitoba/raymond-cormier-secret-recordings-tina-fontaine-murder-trial-1.4534897',
    'http://www.cbc.ca/news/canada/saskatchewan/mmiw-inquiry-high-hopes-answers-1.3707529',
    'https://www.cbc.ca/news/politics/missing-murdered-indigenous-women-inquiry-statistics-1.5176756',
    'https://www.cbc.ca/news/canada/manitoba/human-rights-museum-landfill-search-support-1.6937655',
    'http://www.cbc.ca/news/canada/british-columbia/missing-women-s-inquiry-should-include-aboriginal-men-says-ernie-crey-1.3416631',
    'https://www.cbc.ca/news/indigenous/mmiwg-inquiry-report-1.5158385',
    'https://www.cbc.ca/news/politics/missing-murdered-indigenous-people-filu-permanent-funding-1.6858029',
    'https://www.cbc.ca/news/canada/manitoba/rcmp-amc-newser-dec14-1.7059608',
    'http://www.cbc.ca/news/canada/manitoba/unresolved-cases-of-missing-and-murdered-indigenous-women-1.3651516',
    'https://www.cbc.ca/news/canada/montreal/indigenous-families-have-a-right-to-the-truth-about-children-who-vanished-into-quebec-s-health-system-1.5834902',
    'http://www.cbc.ca/news/canada/montreal/mmiwg-inquiry-resignation-1.4189791',
    'http://canada.onlinenigeria.com/montreal/116056-for-indigenous-people,-inquiries-can-fuel-change-%E2%80%94-but-only-if-governments-act.html',
    'http://www.cbc.ca/news/canada/nova-scotia/missing-murdered-indigenous-women-girls-inquiry-snow-sculpture-1.3991641',
    'http://www.cbc.ca/news/indigenous/delilah-loretta-saunders-chamber-opera-andrew-noseworthy-mmiwg-1.4414857',
    'https://www.cbc.ca/news/canada/manitoba/jaeda-vanderwal-death-family-winnipeg-police-probe-1.5430286',
    'https://www.cbc.ca/news/canada/british-columbia/jessica-patrick-smithers-bc-death-family-friends-memorial-1.5159144',
    'https://www.cbc.ca/news/canada/manitoba/indigenous-women-girls-deaths-landfill-action-needed-manitoba-1.6803494',
    'https://www.mprnews.org/story/2018/04/16/lawmakers-may-study-violence-against-native-american-women',
    'http://www.cbc.ca/news/canada/manitoba/nahanni-fontaine-petition-tina-fontaine-1.4591161',
    'http://www.cbc.ca/news/aboriginal/indigenous-peoples-inquiry-analysis-1.3354869',
    'http://www.cbc.ca/news/canada/thunder-bay/thunder-bay-police-mmiw-training-1.3758791',
    'http://www.cbc.ca/news/indigenous/quebec-police-investigation-val-dor-mmiw-1.4012189',
    'http://www.cbc.ca/news/canada/sudbury/unresolved-series-jane-louise-sutherland-1.4371324',
    'http://nytlive.nytimes.com/womenintheworld/2016/04/07/new-minister-leads-effort-to-right-systemic-wrongs-against-canadas-indigenous-women/',
    'http://www.cbc.ca/news/canada/saskatoon/mother-of-kelly-goforth-welcomes-move-toward-a-national-inquiry-1.3314855',
    'https://www.cbc.ca/news/canada/manitoba/landfill-search-winnipeg-faq-1.6903343',
    'http://investmentunderground.com/2015/12/canada-announces-investigation-into-violence-against/',
    'https://www.cbc.ca/news/canada/manitoba/skibicki-poll-cambria-harris-reaction-1.7115578',
    'https://www.cbc.ca/news/indigenous/genocide-murdered-missing-indigenous-women-inquiry-report-1.5157580',
    'http://www.reddeeradvocate.com/news/families-walk-highway-of-tears-before-mmiw-hearing/',
    'https://www.cbc.ca/news/canada/saskatoon/megan-gallagher-ashley-morin-mmiwg-saskatoon-north-battleford-1.6096488',
    'https://www.cbc.ca/news/canada/saskatchewan/national-day-of-action-mmiwg-1.6606126',
    'https://www.cbc.ca/news/canada/british-columbia/martial-arts-indigenous-women-1.6074679',
    'https://www.cbc.ca/news/canada/manitoba/brady-road-landfill-search-first-nations-woman-found-1.6801738',
    'https://www.cbc.ca/news/canada/manitoba/gazan-landfill-search-manitoba-un-1.6914593',
    'https://www.cbc.ca/news/canada/thunder-bay/headlines/deadly-force-indigenous-1.5680668',
    'https://www.cbc.ca/news/canada/edmonton/mmiwg-report-vigil-edmonton-1.5168576',
    'https://www.cbc.ca/news/canada/saskatchewan/sask-gov-indigenous-fall-session-1.4873764',
    'http://www.cbc.ca/news/canada/cbc-missing-and-murdered-indigenous-women-caj-1.3605440',
    'https://www.cbc.ca/news/canada/nova-scotia/goldboro-lng-workcamp-pieridae-mi-kmaw-opposition-mmiwg-1.6047286',
    'http://www.cbc.ca/news/canada/thunder-bay/missing-murdered-inquiry-details-hajdu-1.3573412',
    'https://cfox.com/news/5345096/bc-indigenous-mmiwg-report/',
    'http://www.cbc.ca/news/indigenous/opinion-foster-care-system-path-to-mmiwg-1.4552407',
    'http://www.tjcnewspaper.com/canada-details-inquiry-on-missing-murdered-indigenous-women-152470/',
    'https://www.cbc.ca/news/canada/manitoba/amc-landfill-search-manitoba-prairie-green-1.7094507',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/innu-inquiry-natuashish-1.6817999',
    'https://www.cbc.ca/news/canada/montreal/families-of-missing-indigenous-children-answers-1.6437662',
    'https://www.cbc.ca/news/canada/manitoba/tessa-perry-homicide-familu-hilda-anderson-pyrz-1.6473000',
    'https://indiancountrytoday.com/news/canadian-minister-pope-needs-to-apologize-to-indigenous',
    'https://www.cbc.ca/news/politics/senator-rcmp-commissioner-resign-1.5612939',
    'http://www.cbc.ca/radio/thecurrent/the-current-for-february-23-2018-1.4547552/injustice-is-a-way-of-indigenous-life-say-advocates-dismayed-at-verdict-in-tina-fontaine-murder-trial-1.4548471',
    'https://www.cbc.ca/news/canada/manitoba/mmiwg-inquiry-winnipeg-visit-1.5171670',
    'http://www.manitoulin.ca/2017/02/08/grieving-father-murdered-woman-applauds-addition-men-national-inquiry/',
    'https://www.cbc.ca/news/canada/manitoba/brady-road-blockade-injunction-hearing-1.6905639',
    'https://www.cbc.ca/news/canada/manitoba/jeremy-skibicki-jury-judge-trial-1.7093471',
    'https://www.cbc.ca/news/canada/manitoba/jeremy-skibicki-opinion-poll-legal-aid-manitoba-1.7114419',
    'http://www.cbc.ca/news/canada/north/march-indigenous-youth-tina-fontaine-1.4558526',
    'https://www.cbc.ca/news/canada/manitoba/jeremy-skibicki-pretrial-day-one-1.7019889',
    'https://www.manitoulin.ca/final-report-from-national-inquiry-into-missing-and-murdered-indigenous-women-and-girls-lists-231-calls-to-action/',
    'http://www.cbc.ca/news/canada/manitoba/tina-fontaine-raymond-cormier-not-guilty-indigenous-leaders-1.4548159',
    'https://www.cbc.ca/news/indigenous/mmiwg-list-cases-1.4856500',
    'https://www.cbc.ca/news/canada/new-brunswick/patty-musgrave-brady-francis-maurice-johnson-elsipogtog-indigenous-1.4968690',
    'http://www.cbc.ca/news/indigenous/indigenous-youth-from-manitoba-attend-daugthers-of-the-vote-1.4013370',
    'http://www.cbc.ca/radio/asithappens/as-it-happens-friday-edition-1.4407258/indigenous-services-minister-says-ottawa-will-participate-in-innu-foster-care-inquiry-1.4407269',
    'http://www.cbc.ca/news/aboriginal/ontario-first-nations-to-hold-inquiry-into-missing-murdered-indigenous-women-1.3220844',
    'http://www.cbc.ca/radio/thehouse/unacceptable-toxicity-at-the-rcmp-needs-to-be-cleaned-up-says-ralph-goodale-1.3453702/carolyn-bennett-shares-lessons-from-pre-inquiry-talks-on-murdered-missing-indigneous-women-1.3453703',
    'http://www.tjcnewspaper.com/canada-launches-investigating-into-aboriginal-women-murder-cases-154607/',
    'https://www.cbc.ca/news/canada/manitoba/mmiwg-red-dress-day-2022-1.6443552',
    'http://www.cbc.ca/news/canada/newfoundland-labrador/nl-inuit-mmiw-1.3512896',
    'http://www.cbc.ca/news/indigenous/mmiwg-inquiry-indigenous-women-streets-1.4139814',
    'http://www.cbc.ca/news/canada/british-columbia/rcmp-civilian-watchdog-ian-mcphail-1.3986818',
    'https://www.cbc.ca/news/canada/manitoba/cambria-harris-fighting-mmiwg-1.6686515',
    'https://www.cbc.ca/news/canada/saskatchewan/missing-and-murdered-indigenous-women-and-girls-funding-1.6644281',
    'https://www.cbc.ca/news/canada/manitoba/manitoba-child-welfare-system-report-1.5946616',
    'https://www.cbc.ca/news/canada/manitoba/helen-betty-osborne-mmiwg-the-pas-manitoba-1.6248405',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/ann-lucas-murder-robert-hillroy-legge-parole-1.5298282',
    'https://www.cbc.ca/news/canada/manitoba/community-groups-response-anniversary-of-tina-fontaine-s-death-1.5249368',
    'https://www.cbc.ca/news/canada/manitoba/red-dress-day-mmiw-crisis-1.6833248',
    'https://www.cbc.ca/news/canada/nova-scotia/nova-scotia-native-women-s-association-zabrina-whitman-resilience-centre-1.6056511',
    'https://www.cbc.ca/news/canada/thunder-bay/thunderbay-moosehidecampaign-mmiwg-1.6840363',
    'https://www.cbc.ca/news/politics/stefanovich-mmiwg-commemoration-kitigan-zibi-anishinabeg-1.5127976',
    'https://www.cbc.ca/news/canada/calgary/fatality-inquiry-tyla-chipaway-cab-driver-social-worker-1.4713195',
    'https://www.cbc.ca/news/canada/montreal/family-of-joyce-echaquan-announce-legal-action-1.5747675',
    'http://www.cbc.ca/news/canada/hamilton/news/hamilton-debate-over-missing-murdered-indigenous-women-gets-heated-1.3261911',
    'http://www.cbc.ca/news/politics/politicians-first-nations-agree-to-another-roundtable-before-end-of-2016-1.2975001',
    'http://www.cbc.ca/news/politics/first-nations-meeting-missing-murdered-indigenous-women-1.3357406',
    'https://www.cbc.ca/news/canada/manitoba/families-mmiwg-trauma-informed-policing-1.6493484',
    'http://www.cbc.ca/news/canada/british-columbia/first-human-resources-policy-after-more-than-a-year-for-mmiwg-inquiry-1.4500439',
    'http://www.cbc.ca/news/canada/thunder-bay/what-a-missing-and-murdered-indigenous-women-inquiry-could-learn-from-an-inquest-in-thunder-bay-ont-1.3354621',
    'https://www.cbc.ca/news/canada/manitoba/lawyer-harvey-pollock-obituary-1.6740928',
    'http://www.cbc.ca/news/canada/edmonton/missing-murdered-women-inquiry-1.4278744',
    'http://www.cbc.ca/news/indigenous/joey-knapaysweet-family-timmins-police-death-1.4553181',
    'https://www.cbc.ca/news/canada/new-brunswick/anns-eye-red-dress-day-fredericton-2024-1.7198100',
    'https://www.cbc.ca/news/canada/british-columbia/on-red-dress-day-coquitlam-students-activist-call-for-action-on-missing-and-murdered-indigenous-women-girls-1.6434106',
    'https://www.cbc.ca/news/canada/manitoba/drag-the-red-new-boat-1.5224263',
    'http://www.cbc.ca/news/canada/manitoba/tina-fontaine-verdict-march-1.4548692',
    'https://www.cbc.ca/news/canada/manitoba/northern-first-nations-victims-intimate-partner-violence-1.5482430',
    'http://www.cbc.ca/news/canada/north/pre-inquiry-mmiw-yellowknife-1.3394144',
    'https://q107.com/news/5346987/mmiwg-report-national-action-plan/',
    'https://www.cbc.ca/news/indigenous/red-handprints-mmiwg-1.5483955',
    'https://www.cbc.ca/news/canada/british-columbia/vancouver-police-under-scrutiny-deaths-indigenous-women-girls-1.6543555',
    'https://www.cbc.ca/news/indigenous/mmiwg-action-plan-update-1.6476685',
    'https://www.cbc.ca/news/canada/newfoundland-labrador/housing-indigenous-women-1.6900014',
    'http://www.cbc.ca/news/politics/missing-murdered-inquiry-1.3355492',
    'http://www.cbc.ca/news/indigenous/families-commemorate-first-official-mmiwg-day-in-manitoba-1.4329473',
    'http://www.cbc.ca/news/politics/mmiw-4000-hajdu-1.3450237',
    'https://www.cbc.ca/news/canada/warning-signs-intimate-partner-homicide-1.6269761',
    'http://www.vueweekly.com/amanda-rheaume-finds-inspiration-in-repetition-for-latest-album/',
    'https://www.cbc.ca/news/canada/edmonton/calls-to-justice-mmiwg-inquiry-marion-buller-1.5383410',
    'https://www.bclocalnews.com/news/kelowna-drums-up-attention-for-missing-and-murdered-indigenous-women/',
    'http://www.cbc.ca/news/canada/british-columbia/red-dress-project-vancouver-1.4334820',
    'http://www.cbc.ca/news/canada/saskatchewan/women-walk-to-spread-awareness-missing-and-murdered-indigenous-women-1.3708041',
    'https://www.cbc.ca/newsinteractives/features/jennifer-catcheway-family-15-years-too-long',
    'https://www.cbc.ca/news/canada/british-columbia/bc-first-nations-justice-council-1.7168998',
    'http://www.cbc.ca/news/canada/montreal/michele-audette-mmiw-inquiry-1.3705514',
    'http://www.cbc.ca/news/canada/manitoba/mmiw-inquiry-questions-unresolved-1.3737771',
    'http://www.cbc.ca/news/canada/manitoba/tina-fontaine-ndinawe-raymond-cormier-trial-1.4521381',
    'http://www.cbc.ca/news/canada/saskatoon/walk-international-women-s-day-1.4571204',
    'https://www.reddeeradvocate.com/news/red-dresses-a-reminder-of-missing-and-murdered-indigenous-women/',
    'http://www.cbc.ca/news/canada/manitoba/raymond-cormier-tina-fontaine-trial-1.4507241',
    'https://www.cloverdalereporter.com/news/lawyer-with-mmiw-inquiry-resigns-citing-government-interference/',
    'http://www.cbc.ca/news/canada/manitoba/dna-expert-raymond-cormier-tina-fontaine-trial-1.4513963',
    'https://q107.com/news/4780016/bc-public-inquiry-money-laundering/',
    'http://www.cbc.ca/news2/interactives/stolen-sisters/',
    'https://www.caledoniacourier.com/news/vigil-downtown-kelowna-to-remember-missing-and-murdered-indigenous-women/',
    'http://www.cbc.ca/news/canada/montreal/quebec-aboriginal-community-inquiry-1.3356317',
    'https://www.asianage.com/world/americas/040619/womens-rights-slipping-gender-equality-under-attack-canadian-pm-justin-trudeau.html',
    'http://www.cbc.ca/news/canada/manitoba/aboriginal-justice-inquiry-colten-boushie-gerald-stanley-jury-1.4532394',
    'http://www.cbc.ca/news/politics/murdered-missing-inquiry-macdonald-1.3743744']
# urls = urls[:100]
print(len(urls), "urls")


async def check_url(playwright, url, semaphore):
    async with semaphore:  # Use the semaphore to limit concurrency
        browser = await playwright.chromium.launch(headless=True)
        page = await browser.new_page()

        try:
            response = await page.goto(url, timeout=60000)

            # Check if the request was successful
            if response.status == 200:
                # Extract title and body
                title = await page.title()
                body = await page.inner_text('body')  # Adjust selector as needed

                # Save to JSON file
                with open('data/url_data/new_url_data.json', 'a') as f:
                    json.dump({'url': url, 'title': title, 'body': body}, f)
                    f.write('\n')

                return True
            else:
                bad_requests.append(url)
                return False
        except Exception as e:
            # Handle exceptions like connection errors
            could_not_access.append(url)
            return False
        finally:
            await browser.close()


async def main():
    async with async_playwright() as p:
        # Create a semaphore to limit concurrency
        semaphore = asyncio.Semaphore(15)  # Adjust the concurrency level as needed
        first_pass_start_time = datetime.datetime.now()

        # First pass: Attempt to access all URLs concurrently
        tasks = [asyncio.create_task(check_url(p, url, semaphore)) for url in urls]
        await asyncio.gather(*tasks)

        first_pass_end_time = datetime.datetime.now()

        first_pass_elapsed_time = first_pass_end_time - first_pass_start_time

        print("""
        . . . . . . . .
        First pass done 
        . . . . . . . .
        """)
        print(f"First pass took {first_pass_elapsed_time}.")

        # Second pass: Attempt to reaccess URLs that could not be accessed initially concurrently
        recheck_tasks = [asyncio.create_task(check_url(p, url, semaphore)) for url in could_not_access]
        await asyncio.gather(*recheck_tasks)


start_time = datetime.datetime.now()

# Run the main coroutine
asyncio.run(main())

end_time = datetime.datetime.now()

elapsed_time = end_time - start_time

print(f"Code took {elapsed_time}.")

# Print the lists
print("Bad Requests:", bad_requests)
print("Could Not Access:", could_not_access)

print(len(could_not_access), "urls coudn't be accesed")